### ISSUE TITLE
Watcher isn't cancelled on drop

### ISSUE THREAD

**Issue by teozkr** [kube-rs/kube-rs#1005]
### Discussed in https://github.com/kube-rs/kube-rs/discussions/1004

<div type='discussions-op-text'>

<sup>Originally posted by **goenning** September  9, 2022</sup>
Hi all,

I have a watcher running on a tokio task, something like this:

```
let handle = spawn(async move {
    let w = watcher(api, params).backoff(default_backoff());

    pin_mut!(w);

    loop {
        let event = w.try_next().await;

        match event {
            Ok(Some(Event::Applied(mut e))) => {
                ...
```

Eventually I want to cancel the watcher so I just do a `handle.abort()`. I thought this would be enough to cancel the underlaying request, but it doesn't. While using proxyman, the watch HTTP request is still active, and it stays active until the next event arrives or it times out. 

Is there a way to cancel the request as well? It's a minor optimization, but I'd prefer not having unnecessary open connections.

Thank you!</div>

**Comment by teozkr** [comment]
This seems to be a bug in `Api::watch` (or an underlying layer), I can repro the issue when using this modified variant of our `event_watcher` example: https://gist.github.com/teozkr/2015675ab3fdf8f02e5d65aae670ce4a

**Comment by teozkr** [comment]
I'm not seeing anything in `Api::watch` or `Client::request_events`/`Client::send` that should be spawning any tasks.. Might be a middleware issue?

**Comment by teozkr** [comment]
Nevermind! This was actually a bad repro on my part. If I drop `ew` then it does cancel correctly for me (https://gist.github.com/teozkr/e337571fa40e345a3ca527a39a96bc4e), both with `Api::watch` and `watcher`.

**Comment by AnishTiwari** [comment]
@nightkr , can you please share the gist code(404), I'm facing the same issue, somehow the watcher is not getting destroyed on handle.abort(); .
