### ISSUE TITLE
Run examples through memory-profiler

### ISSUE THREAD

**Issue by clux** [kube-rs/kube-rs#14]
https://github.com/nokia/memory-profiler

Being a bit liberal with allocations everywhere because it's not that critical. Just wanna make sure the reflectors/informers aren't leaking memory when running for a long time.

**Comment by nikolay-te** [comment]
I'm currently investigating an issue with code that I wrote that seems to be leaking some memory. I use two reflectors in my code and what I've noticed is that over time memory usage grows from around 20-30M at startup to 250M+ for a maybe month and a half.

A few hours of running the code under Instruments on OS X potentially showed that the Reflector might be the source, and this led me to this post. I'll try to post an update if I manage to pinpoint it

**Comment by clux** [comment]
Thank you. Yeah, I have have a `Reflector` using app in production that is leaking memory and periodically being restarted from the OOM killer, so it's likely that it's likely. Mine seems to leak a couple of hundred megs a week, but it's a pretty big CRD. Not sure where it would leak though, not doing anything obviously weird.

Regardless, should mention that reflectors are getting a less clone heavy rewrite in #258 (likely to land soon).

**Comment by nikolay-te** [comment]
I'm trying now running this with the memory-profiler (finally managed to build the cli on mac), and I'm seeing quite a lot of these allocations under "Leaked allocations", :
```
#0 [libc-2.27.so] clone
#1 [libpthread-2.27.so] start_thread
#2 [kube-canary] std::sys::unix::thread::Thread::new::thread_start [thread.rs:87]
#3 [kube-canary] <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once [boxed.rs:1076]
#4 [kube-canary] <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once [boxed.rs:1076]
#5 [kube-canary] core::ops::function::FnOnce::call_once{{vtable.shim}} [function.rs:232]
#6 [kube-canary] std::thread::Builder::spawn_unchecked::{{closure}} [mod.rs:474]
#7 [kube-canary] std::panic::catch_unwind [panic.rs:394]
#8 [kube-canary] std::panicking::try [panicking.rs:274]
#9 [kube-canary] std::panicking::try::do_call [panicking.rs:297]
#10 [kube-canary] <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once [panic.rs:318]
#11 [kube-canary] std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}} [mod.rs:475]
#12 [kube-canary] std::sys_common::backtrace::__rust_begin_short_backtrace [backtrace.rs:130]
#13 [kube-canary] tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}} [pool.rs:209]
#14 [kube-canary] tokio::runtime::handle::Handle::enter [handle.rs:76]
#15 [kube-canary] tokio::runtime::context::enter [context.rs:72]
#16 [kube-canary] tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}::{{closure}} [pool.rs:210]
#17 [kube-canary] tokio::runtime::blocking::pool::Inner::run [pool.rs:230]
#18 [kube-canary] tokio::runtime::task::Notified<S>::run [mod.rs:169]
#19 [kube-canary] tokio::runtime::task::raw::RawTask::poll [raw.rs:66]
#20 [kube-canary] tokio::runtime::task::harness::Harness<T,S>::poll [harness.rs:89]
#21 [kube-canary] std::panic::catch_unwind [panic.rs:394]
#22 [kube-canary] std::panicking::try [panicking.rs:274]
#23 [kube-canary] std::panicking::try::do_call [panicking.rs:297]
#24 [kube-canary] <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once [panic.rs:318]
#25 [kube-canary] core::ops::function::FnOnce::call_once [function.rs:232]
#26 [kube-canary] tokio::runtime::task::harness::Harness<T,S>::poll::{{closure}} [harness.rs:107]
#27 [kube-canary] tokio::runtime::task::core::Core<T,S>::poll [core.rs:158]
#28 [kube-canary] tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut [unsafe_cell.rs:14]
#29 [kube-canary] tokio::runtime::task::core::Core<T,S>::poll::{{closure}} [core.rs:173]
#30 [kube-canary] <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll [task.rs:38]
#31 [kube-canary] tokio::runtime::thread_pool::worker::Launch::launch::{{closure}} [worker.rs:281]
#32 [kube-canary] tokio::runtime::thread_pool::worker::run [worker.rs:302]
#33 [kube-canary] tokio::macros::scoped_tls::ScopedKey<T>::set [scoped_tls.rs:63]
#34 [kube-canary] tokio::runtime::thread_pool::worker::run::{{closure}} [worker.rs:305]
#35 [kube-canary] tokio::runtime::thread_pool::worker::Context::run [worker.rs:320]
#36 [kube-canary] tokio::runtime::thread_pool::worker::Context::run_task [worker.rs:348]
#37 [kube-canary] tokio::coop::budget [coop.rs:96]
#38 [kube-canary] tokio::coop::with_budget [coop.rs:120]
#39 [kube-canary] std::thread::local::LocalKey<T>::with [local.rs:239]
#40 [kube-canary] std::thread::local::LocalKey<T>::try_with [local.rs:263]
#41 [kube-canary] tokio::coop::with_budget::{{closure}} [coop.rs:127]
#42 [kube-canary] tokio::runtime::thread_pool::worker::Context::run_task::{{closure}} [worker.rs:349]
#43 [kube-canary] tokio::runtime::task::Notified<S>::run [mod.rs:169]
#44 [kube-canary] tokio::runtime::task::raw::RawTask::poll [raw.rs:66]
#45 [kube-canary] tokio::runtime::task::harness::Harness<T,S>::poll [harness.rs:89]
#46 [kube-canary] std::panic::catch_unwind [panic.rs:394]
#47 [kube-canary] std::panicking::try [panicking.rs:274]
#48 [kube-canary] std::panicking::try::do_call [panicking.rs:297]
#49 [kube-canary] <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once [panic.rs:318]
#50 [kube-canary] core::ops::function::FnOnce::call_once [function.rs:232]
#51 [kube-canary] tokio::runtime::task::harness::Harness<T,S>::poll::{{closure}} [harness.rs:107]
#52 [kube-canary] tokio::runtime::task::core::Core<T,S>::poll [core.rs:158]
#53 [kube-canary] tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut [unsafe_cell.rs:14]
#54 [kube-canary] tokio::runtime::task::core::Core<T,S>::poll::{{closure}} [core.rs:173]
#55 [kube-canary] <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll [mod.rs:73]
#56 [kube-canary] kube_canary::k8s::KubeReflector::reflector_task::{{closure}} [k8s.rs:315]
#57 [kube-canary] <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll [mod.rs:73]
#58 [kube-canary] kube::runtime::reflector::Reflector<K>::run::{{closure}} [reflector.rs:58]
#59 [kube-canary] <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll [mod.rs:73]
#60 [kube-canary] kube::runtime::reflector::Reflector<K>::reset::{{closure}} [reflector.rs:163]
#61 [kube-canary] <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll [mod.rs:73]
#62 [kube-canary] kube::runtime::reflector::Reflector<K>::get_full_resource_entries::{{closure}} [reflector.rs:173]
#63 [kube-canary] <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll [mod.rs:73]
#64 [kube-canary] kube::api::typed::Api<K>::list::{{closure}} [typed.rs:105]
#65 [kube-canary] kube::api::resource::Resource::list [resource.rs:312]
#66 [kube-canary] kube::api::resource::Resource::make_url [resource.rs:76]
#67 [kube-canary] inflector::string::pluralize::to_plural [mod.rs:142]
#68 [kube-canary] <inflector::string::pluralize::RULES as core::ops::deref::Deref>::deref [lib.rs:144]
#69 [kube-canary] <inflector::string::pluralize::RULES as core::ops::deref::Deref>::deref::__stability [lib.rs:142]
#70 [kube-canary] lazy_static::lazy::Lazy<T>::get [core_lazy.rs:21]
#71 [kube-canary] spin::once::Once<T>::call_once [once.rs:110]
#72 [kube-canary] core::ops::function::FnOnce::call_once [function.rs:232]
#73 [kube-canary] <inflector::string::pluralize::RULES as core::ops::deref::Deref>::deref::__static_ref_initialize [mod.rs:23]
#74 [kube-canary] regex::re_unicode::Regex::new [re_unicode.rs:175]
#75 [kube-canary] regex::re_builder::unicode::RegexBuilder::build [re_builder.rs:69]
#76 [kube-canary] regex::exec::ExecBuilder::build [exec.rs:308]
#77 [kube-canary] regex::compile::Compiler::compile [compile.rs:116]
#78 [kube-canary] regex::compile::Compiler::compile_one [compile.rs:144]
#79 [kube-canary] regex::compile::Compiler::compile_finish [compile.rs:187]
#80 [kube-canary] core::iter::traits::iterator::Iterator::collect [iterator.rs:1671]
#81 [kube-canary] <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter [vec.rs:1978]
#82 [kube-canary] <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter [vec.rs:2103]
#83 [kube-canary] <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::spec_extend [vec.rs:2119]
#84 [kube-canary] alloc::vec::Vec<T>::reserve [vec.rs:500]
#85 [kube-canary] alloc::raw_vec::RawVec<T,A>::reserve [raw_vec.rs:267]
#86 [kube-canary] alloc::raw_vec::RawVec<T,A>::try_reserve [raw_vec.rs:281]
#87 [kube-canary] alloc::raw_vec::RawVec<T,A>::grow_amortized [raw_vec.rs:440]
#88 [kube-canary] alloc::raw_vec::finish_grow
```

The `regex` use seems to be coming from the `inflector` crate, and specifically the few calls to `inflector::string::pluralize::to_plural` in `resource.rs` and `custom_resource.rs`

Seems like the regex crate is using thread-local cache of regexes, I wonder if that could be the cause of the leaks?

**Comment by clux** [comment]
Oh, interesting. We could try to inline `to_plural` (that's the only thing we use from inflector), and replace it with a dumb function that adds on a trailing "s" while we are testing. Should only be the one in `resource.rs` that's used a lot.

**Comment by nikolay-te** [comment]
Yeah, I'm going to try to do that and see if it changes things.

**Comment by nikolay-te** [comment]
So, I've replaced the single use of `to_plural()` in `resource.rs` with a `format!("{}s", &self.kind.to_ascii_lowercase())`.
The first thing I'm noticing is before on start my program was using around ~26MB ram and started climbing from there. Right now it is using only 9MB.
I'll leave it running overnight and report back.

**Comment by clux** [comment]
Awesome! Fingers crossed.
Thanks a lot for investigating.

**Comment by teozkr** [comment]
Seems related to https://github.com/rust-lang/regex/issues/362. So I guess the actual problem here is `inflector::string::pluralize::RULES` keeping the `Regex` as a constant..

**Comment by nikolay-te** [comment]
Unfortunately, it seems while significantly reducing the memory usage, the change did not fix the leak. I still see the memory is still growing since the restart yesterday:
<img width="1026" alt="Screen Shot 2020-07-18 at 09 17 14" src="https://user-images.githubusercontent.com/46969469/87846344-d5e06c00-c8d7-11ea-904c-ef28103a9274.png">

**Comment by clux** [comment]
If there's a significant memory reduction then you have at least fixed one leak. Appreciate identifying that regardless.

**Comment by nikolay-te** [comment]
This is now running 0.37.0 with the new streaming reflectors from kube-runtime. It does seem better so far. <img width="735" alt="Screen Shot 2020-07-22 at 17 34 23" src="https://user-images.githubusercontent.com/46969469/88189432-b895ff80-cc41-11ea-9578-4efe5f6e8a40.png">

**Comment by clux** [comment]
Awesome! Is this still with the inflector fix in place? I'd love to have a PR for a non-leaking replacement for it!

**Comment by nikolay-te** [comment]
No, this is without the hack I tested earlier. I can certainly open a PR with that, but I'm not sure what the correct way to fix it as it won't pluralize properly all cases.
Maybe a hand-rolled version of only the pluralize function without the regex caching?

Finally, I'm not sure it was actually leaking per se, as the memory usage was still increasing even with the bypass of the Inflector's pluralize, it seems it was just using too much memory (e.g. keeping a thread-local regex cache per each tokio worker thread).

**Comment by clux** [comment]
Oh, interesting. Well, maybe it's not an issue then. At least if you're seeing consistent memory use without hacking it \o/

I did have a look at inflector source earlier and saw a bunch of `lazy_statics` which i thought was one the recommended way to cache regexes, so was a bit surprised hear that it leaked.

**Comment by teozkr** [comment]
Oh, ouch. I see where the inflector is actually used now. So we're basically just hoping that the `inflector` gives the same result as the K8s mappings (which can actually be specified manually, and have no guarantee of being grammatically correct, not that `inflector` is going to be perfect either).

That makes some sense for `kube-derive` (as an overridable default), but we should try to avoid that at runtime. Seems like the core problem is that `k8s_openapi::Resource` doesn't have a `RESOURCE` const, so let's try to fix that?

**Comment by clux** [comment]
Forgot to close this after the fixes, maybe I forgot to double check. But for posterity, reflectors and watchers don't create any leaks afaict (here's a deployment tracking 1400 pod metadata objects through reflectors over a week):
![Screenshot from 2021-11-04 00-06-57](https://user-images.githubusercontent.com/134092/140235773-a068a9e0-6d66-46db-9206-3b6c9df500f7.png)

If we had a leak at this point, with proper instrumentation (e.g. kube-state-metrics + kubernetes-mixin) people would report quickly find and report this.
