### ISSUE TITLE
Rate Limiting Strategies

### ISSUE THREAD

**Issue by theduke** [kube-rs/kube-rs#500]
The official Go client provides rate limiters to prevent spamming the API with requests.

See https://pkg.go.dev/k8s.io/client-go@v0.21.0/util/workqueue

It would be nice to get similar functionality in this project.

Useful would be:

* Global rate limiter for the whole client
* `Api<T>` specific rate limiter
* Pluggable rate limiting strategies, like in the Go client (exponential backoff, etc)

**Comment by MikailBag** [comment]
I think kube should somehow reuse existing rate limit implementations from the Tower ecosystem.

In that case, this issue looks like "ability to inject arbitrary Services on client or Api level".

**Comment by kazk** [comment]
Custom client with [layers](https://docs.rs/tower/0.4.8/tower/trait.Layer.html) is now supported. You can do this for global:

```rust
use kube::{client::ConfigExt, Client, Config};
use tower::{limit::RateLimitLayer, ServiceBuilder};

let config = Config::infer().await?;
let https = config.native_tls_https_connector()?;
let client = Client::new(
    ServiceBuilder::new()
        .layer(config.base_uri_layer())
        .layer(RateLimitLayer::new(num, duration))
        .service(hyper::Client::builder().build(https))
);
```

**Comment by theduke** [comment]
Awesome, thanks!

**Comment by clux** [comment]
Summary of status after going through issues a bit.

- [x] 1. Global rate limiter strategy [above](https://github.com/kube-rs/kube-rs/issues/500#issuecomment-855319223)
- [x] 2. Invidual api calls (something that glues `backoff` with `futures` - like [tokio-retry](https://github.com/srijs/rust-tokio-retry))
- [ ] 3. `workqueue` based system on the `Api` type or better ways

For 2; It would be **nice to have some examples showcasin individual method retries** here.

For 3, not sure we should do this here. It would be complicated. This could be tackled in the `RateLimitLayer` in `tower` by making it configurable based on paths, or by injecting an optional rate limiter deep within `Api`, or by thinking about if we could clone the `Client` in such a way that we could customize the layers per copy. (Pretty sure that if we instantiate two instances of a `Custom` client, you'd be able to get different rate limit layers on each of them. But it's not designed for that). Anyway, **investigative work here would be appreciated**.
