### ISSUE TITLE
Refine our logo

### ISSUE THREAD

**Issue by clux** [kube-rs/kube-rs#570]
Edit: We played around with logos a bit one week here together, and we are using the final product from the comment below in https://github.com/kube-rs/kube-rs/issues/570#issuecomment-882128469. But we do need to soften that up a bit to make it proper (it doesn't divide cleanly atm).

<details><summary>old experiment</summary>
<p>
had some fun trying the obvious logo concept in my head (crossing the rust gear with the kubernetes wheel):

![kube-rs-concept-blur](https://user-images.githubusercontent.com/134092/123690749-a4448480-d84c-11eb-81c0-6284eb9e2796.png)

now; this is a sketch, and i'm a terrible graphics person: colors are pretty random, alignment is off, edges are awful, and as such have no usable thing.

but opening this fun issue anyway. is this a good concept? anyone have better ideas? anyone want to try to make a better version / different idea? contributions welcome!
</p>
</details>

**Comment by kazk** [comment]
I'm terrible at graphics as well. Links to Rust and Kubernetes logos if anyone wants to try combining them:

- https://github.com/rust-lang/rust-artwork/blob/master/logo
  - https://www.rust-lang.org/policies/media-guide
- https://github.com/kubernetes/kubernetes/tree/master/logo
- https://cncf-branding.netlify.app/projects/kubernetes/
  - https://github.com/cncf/artwork/tree/master/projects/kubernetes

There's gear only version https://github.com/rust-lang/rust-artwork/blob/master/logo/rust-logo-gear-only.svg

![image](https://user-images.githubusercontent.com/639336/123706136-bd354180-d81c-11eb-8e2e-650fa5044e5b.png)

**Comment by clux** [comment]
![kubelogoidea4](https://user-images.githubusercontent.com/134092/123719120-a6243d00-d878-11eb-9244-2bdffcf84f8f.png)

tried some more; putting gears in gears, i don't know what i am doing

**Comment by teozkr** [comment]
The colours are a bit wonky, but otherwise I quite liked the first attempt.

**Comment by clux** [comment]
Did a straight blend of the large png [official kubernetes logo](https://github.com/kubernetes/kubernetes/blob/master/logo/logo.png) and the official svg gear (scaled to 5400px to fit the png)

![kube-bw-blend](https://user-images.githubusercontent.com/134092/126084713-59ae550f-692d-4034-b292-e33f18167f30.png)

Removed the rivet parts of the gear (because 5 rivets to 7 spokes will never look clean) and superimposed the rust logo inverted.
I think someone who can make a customized gear with a correct number of gear ridges (a multiple of 7 presumably) would be ideal (currently, this looks better on some parts of the handle than others).

**Comment by clux** [comment]
Ok, this is actually required to progress at the donation issue. To be added to the landscape we need a pure svg version of the logo to [submit to the landscape repo](https://github.com/cncf/landscape#new-entries). Will see if I can try that tomorrow at some point.

**Comment by clux** [comment]
It seems CNCF provides help for this: https://www.cncf.io/services-for-projects/#design-and-aesthetics - might be faster than having me learn this stuff properly. Will ask.

**Comment by clux** [comment]
Good news! We have gotten logo sketches from CNCF designer Alex, and she's done a great job imo:

[kube-rs-logos_v1.pdf](https://github.com/kube-rs/kube-rs/files/7947302/kube-rs-logos_v1.pdf)

Personally there are three here I really like: 4, 3, 2 in order of preference:
- 4 is has a new take on where to place the gears, includes the bounding heptagon, and uses rust colors - think this will look great everywhere
- 3 or 1 is what we asked for, fixed the gears, and has more rust colors
- 2 an improvement of the release team variant which is done much better here. blue colors also work kind of nice

WDYT @kazk , @teozkr ? Are you happy with any of these - what are your preferences?
We can probably ask to shift colours around a bit if needed.

**Comment by kazk** [comment]
Nice!

```
1 2 3
4 5 6
7 8 9
```

![image](https://user-images.githubusercontent.com/639336/151290007-c8de90cb-fec0-4840-8f24-8ca21fe32bce.png)

My preference: `1 = 8 > 6 > 4 >= 2`

I like the simplicity of 1 and 8. 8 is clearly Kubernetes + Rust, and should look good with just black too. 1 might look too similar to the original Kubernetes wheel when small, but the color helps. 6 is fun and will stand out, but it might be better to use Ferris like [Krator](https://www.cncf.io/projects/krator/). 4 and 2 are not bad, but I think the wheel is too hidden.

I prefer the font used in 1-3.
Is it required to include `-rs`? Is it possible to deemphasize? kube<sub>rs</sub>?

**Comment by clux** [comment]
Yeah, the crab variants would benefit from having more of a likeness to Ferris, like literally having Ferris steering the wheel, or some other blue crab with Ferris like features (in the spirit of Corro the urchin).

I can ask to de-emphazise -rs. A subscript sounds smart to me. Suffix was kind of just there as a way to clarify that it was rust as I started having a lot of repos..

Most of the logos convey rust + kubernetes well. I think the advantage to me of 1-5 over 7,8 is that the systems looks connected. The gears are part of the system to drive the wheel - whereas 7,8 looks like a two separated structures that ultimately don't move together.

**Comment by teozkr** [comment]
I think having some sort of crab is more recognizable (especially in grayscale) then the Rust Cog, even if it's not Ferris specifically. My preference would be `6 > 1 > 2`, but I think most of the dual-colour ones (including 6 and 2) could use a bit more contrast between the two colours. 6 looks particularly faint, as it is right now. I like @clux's idea of Ferris steering the wheel, but that seems like a fairly extensive do-over (depending on how much we can request from the CNCF, and their current workload).

As for the -rs discussion, I think it's important (from a not-wanting-to-get-sued perspective, if nothing else) that we don't seem like we're affiliated with either the Kubernetes or Rust projects. kube-rs already sounds dangerously close to "it's the Kube project's Rust client", but I think kube<sub>rs</sub> moves even closer in that direction.

**Comment by clux** [comment]
it is possible that subscript can be interpreted less favourably w.r.t. [cncf trademark guidelines](https://www.linuxfoundation.org/trademark-usage/) - but i feel that as we are both (kube + k8s) under CNCF - even if not directly affiliated - if they are making us a logo, they get to be in charge of that cohesion.

on the other hand i can see it having other problems; putting an asymmetrical subscript into an otherwise symmetrical logo would probably not be that easy.

**Comment by clux** [comment]
so will give some general points of feedback and see if they are happy with making some tweaks:

- the gears do not actually align with the wheels (num_gears is not a multiple of num_spokes) and looks a bit more awkward zoomed in (just noticed)
- font used in top row preferable (to at least me and kazk)
- all of us like 1 and 2 as solid variants that will look good in most use cases (dark / light / circular avatars)
- we are also very positive on a crab based logo/variant (but we would want see it have more of a Ferris likeness first)

**Comment by clux** [comment]
New logos: [kube-rs-logos_v2.pdf](https://github.com/kube-rs/kube-rs/files/7965229/kube-rs-logos_v2.pdf)
![Screenshot from 2022-01-30 03-02-19](https://user-images.githubusercontent.com/134092/151685074-50886c0b-7f54-4d64-ac9b-578d9ba0b103.png)

We got some more straight-on crab ideas. And the gears have been fixed! I like 1 and 2 again (different colors here this time).
4 has potential - but it's got a little too much going on atm with the patterns inside where the face sits. Maybe it would work if the face was one color but the body was in the heptagon shape with gears?

**Comment by teozkr** [comment]
Tried to simplify 4 from v2 a bit (yes, I know the fills look janky):

![image](https://user-images.githubusercontent.com/649832/151685395-7cb957e5-9e2d-48ca-98a5-13263413a5c3.png)

I kind of like 2, but by removing the inner ring of spokes (to get a reasonable "face place") I'm not sure it's really recognizable as a wheel anymore, further diminishing our association with the K8s side of things. I tried to remedy that by bringing in the dark blue as an accent colour, but if anything I feel like that just made the remaining spokes even less recognizable.

Perhaps it would make sense to drop the face completely but keep the legs?

**Comment by clux** [comment]
yeah.. it's hard to discern the original purpose from this. your edit makes it a bit better, but it strikes me as a bit of a mayan calendar disaster crab either way.

i'm thinking that maybe we should **just go with some colour variation of 1** here? it's the least surprising logo, it's the cleanest (now with alignment done), and will look good in all cases (circular avatars / dark / light).

maybe we can revisit the crab idea and maybe use it as a mascot idea - like what rust does with ferris - down the line. but starting to think that we should **not** have a ferris based thing as our **main logo**.

**Comment by teozkr** [comment]
Sounds good.

**Comment by clux** [comment]
Have requested a final svg of the 1st one, and if time allows, some color options. have figured out (the very basics) of how to operate `inkscape` now though, so the last part (coming up with color schemes) should be doable on my end.

[got these more glamorous variants after a couple of hours hacking away with filters](https://gist.github.com/clux/03393cf29c449b98ae8c945ca57a4637) - ultimately not super useful but i thought they ended up looking cool regardless

**Comment by clux** [comment]
ok, haven't heard back from the designer, but maybe i tipped her off that i can kind of work inkscape now. so let's talk colors/gradiants/tweaks. here are some ideas from a few hours - need at least one that's good on a light theme and one that's good on dark.

## blues
![export_blues](https://user-images.githubusercontent.com/134092/153760174-d86d4e0c-eeae-4e07-8e46-ed574b5803ae.png)

## oranges
![exports_orange](https://user-images.githubusercontent.com/134092/153760179-7eac2b38-db7e-478a-9faf-0482f65107b4.png)

## whites
![export_whites](https://user-images.githubusercontent.com/134092/153760201-ea843990-bf4e-4116-8428-0690cacc163b.png)

## blacks
![export_blacks](https://user-images.githubusercontent.com/134092/153760206-8ac16754-62f1-43d2-aee3-3bae6832e680.png)

**Comment by kazk** [comment]
Black with colors inside looks pretty cool, but I like the simple transparent blue/black/white.

> need at least one that's good on a light theme and one that's good on dark.

Most [projects](https://github.com/cncf/artwork/blob/master/examples/sandbox.md) have color/black/white variants, so I'd try to follow that. Even if we decide we want two colored variations for light/dark themes, I think it's better to use different shades of a similar/same color than two different colors.

**Comment by teozkr** [comment]
I like the black with flat orange spaces between the spokes. Maybe add a white outline so it works well on both dark and light backgrounds. The primarily white ones look quite overwhelming on a dark background (might also be the size, to be fair we'd probably rarely actually want it that huge).

The 3D axles look kind of awkward on top of the otherwise flat and straight-frontal wheels. My first impression was "oh, a bunch of misaligned ovals" until it finally clicked.

**Comment by kazk** [comment]
> The 3D axles

Huh, I wasn't sure what that was.
Looked like an eye from the :sun_with_face::crab:

<img src="https://user-images.githubusercontent.com/639336/153974470-e2c6db39-f846-4700-81b7-8bbd0055a3e1.png" height=140><img src="https://user-images.githubusercontent.com/639336/153975845-bc467db2-5b6c-4524-8a27-6facd4c3a631.png" height=140>

**Comment by clux** [comment]
yeah, i experimented with a single eye, to give it that hidden octopus / kraken feel. i guess it's too subtle to use :-)

**Comment by clux** [comment]
needing good variants in black and white breaks my design skills a bit when venturing into color land so have just done some plain bw in two variants as shown here:

![white_blackborder](https://user-images.githubusercontent.com/134092/155096166-424b89cc-beb9-419f-8a53-6a9325983aac.png)
![black_whiteborder](https://user-images.githubusercontent.com/134092/155096175-326dfcfa-0c1c-43d9-9f86-c654c74f930b.png)

as suggested, i added a light border so that it's always visible if the dark-mode media query fails (view this comment in github dark / light mode to see difference). black on white, and white on black both look the best, but they are at least discernible now with black on black and white on white.

i did also [try to get some colors](https://gist.github.com/clux/450fa3be029c8950e962b3adbd03bded) (with e.g. gradient or solid inner color), but not finding a combination that's particularly intriguing with a block color beyond b/w, so probably going to put a pin in it for now unless anyone has any bright ideas color wise. i kind of like the black / white solutions best so far anyway, and starting to feel like i kind of just want to get this done at this point - and submit the upstream PR to cncf/landscape so we can close the donation issue - then potentially look at refining more at another time. at least this fixes spokes, has the SVG scaling, and gave me enough skills to use inkscape to use it in anger.

(there's also an incentive to getting this done soon: kubecon valencia is coming up, and want to apply for project office hours for some light PR (as i'll be there) - the deadline for that is this friday).

**Comment by teozkr** [comment]
In concept I prefer the black one, but somehow the white one has much much better antialiasing.

**Comment by clux** [comment]
that could just be down to the way i exported it from an svg. here is the svg version - which should look better:
![kube](https://user-images.githubusercontent.com/134092/155107778-68cf7ad4-9067-4066-8896-46dd05961217.svg)

**Comment by kazk** [comment]
The black one looks good.

I think you need to convert the text (`kube-rs`) to paths, so it doesn't depend on the font.

**Comment by clux** [comment]
ah, TIL. here it should be converted:
![kube path](https://user-images.githubusercontent.com/134092/155113732-6759b80d-c3f6-432f-a593-697ac7e8ee24.svg)

**Comment by kazk** [comment]
<img src="https://user-images.githubusercontent.com/639336/155115130-758a8ba9-e209-42de-bf6d-cde7be3ed86f.svg" width="256">&nbsp;&nbsp;&nbsp;&nbsp;<img src="https://user-images.githubusercontent.com/639336/155115244-d31e3dcf-a80c-4cb5-b509-3cbe095dbfb1.svg" width="256">&nbsp;&nbsp;&nbsp;&nbsp;<img src="https://user-images.githubusercontent.com/639336/155115328-c6d9b14a-c65f-436d-a747-3497b890b8c3.svg" width="256">

<img src="https://user-images.githubusercontent.com/639336/155115602-cb5f4c64-24a3-4921-b5e9-0e4d5a656c6b.svg" width=256>&nbsp;&nbsp;&nbsp;&nbsp;<img src="https://user-images.githubusercontent.com/639336/155115682-35f98594-8fd7-41d5-bc4b-3f1e62872860.svg" width=256>&nbsp;&nbsp;&nbsp;&nbsp;<img src="https://user-images.githubusercontent.com/639336/155115713-4433e84d-3560-4611-8fba-1bf9629b6405.svg" width=256>

**Comment by clux** [comment]
ah, nice! i saw there were some stray properties in there. some of them are fallbacks like aria properties, but the [cncf logo requirements](https://github.com/cncf/landscape#logos) says nothing about maintaining these (and we can always use aria attribs on the image tag anyway). thanks for this! i see inkscape has options like this as well now in retrospect.

i'll take the right-most ones for the official svg if that's OK? (the stroke radius looks nicest to me when it's clear in the accidental black-black or white-white case - and the stroke radius is irrelevant otherwise in the correct media-query case)

**Comment by kazk** [comment]
> i'll take the right-most ones for the official svg if that's OK?

Sure

**Comment by clux** [comment]
thanks a lot!
i'll try it out on the website first to double check, it's possible that the border looks big on a non-black background on second thought.

**Comment by clux** [comment]
actually ended up with the lower stroke radius, since it was quite visible on the `slate` themed background: [kube.rs](https://kube.rs/) (switch the themes around to see difference)

**Comment by kazk** [comment]
Looks good :+1:

---
 
`<br>` in between the images should be removed. It pushes the dark one down (the logo moves when you switch the theme).

![image](https://user-images.githubusercontent.com/639336/155124902-30a4167c-e14f-41c2-a0f0-453ab1c544a3.png)

**Comment by kazk** [comment]
`CNAME` should be moved to `docs/CNAME` so `mkdocs` will include it in the published branch. Current setup will break on each deploy.

> So that the file does not get removed the next time you deploy, you need to copy the file to your `docs_dir`. With the file properly included in your `docs_dir`, MkDocs will include the file in your built site and push it to your "pages" branch each time you run the `gh-deploy` command.
> [Deploying Your Docs - MkDocs](https://www.mkdocs.org/user-guide/deploying-your-docs/)

**Comment by clux** [comment]
ah, yeah, i [just noticed](https://github.com/kube-rs/website/commit/183ee329fe49839ee386509ee2f31c74fbc8a038)) that was the problem, and it seems to work now!

**Comment by teozkr** [comment]
Ahh, good catch.
