### ISSUE TITLE
donation: CLA/DCO setup

### ISSUE THREAD

**Issue by clux** [kube-rs/kube-rs#585]
discussions about the potential process to get a CLA/DCO and how to do that **IF** we decide to donate the repo to CNCF (#584).

Quite a lot of work if it requires retroactive approval from past contributors.

One project that relicensed through github issue checkmarks: https://github.com/gfx-rs/wgpu/issues/1473
Wonder if that approach would be sufficient? People can delete issue comments.

[CNCF individual CLA](https://github.com/cncf/cla/blob/master/individual-cla.pdf) certainly seems like it has more clauses than to just allow re-licensing.

The https://github.com/cla-assistant/cla-assistant from [Sönke's comment below](https://github.com/clux/kube-rs/issues/585#issuecomment-878371721) seems the most promising.

**Comment by soenkeliebau** [comment]
The easiest way might be to activate a cla assistant on the repo (for example [1]) - this usually generates a link which you could post under this issue, tag all contributors and ask them to sign the CLA.
That would hopefully gather a sizeable initial batch (I hesitate to guess a percentage here).

Give that a week or two and then we can get to work on trying to contact the missing people directly and talking to them. 

The number of contributors is not extremely large, so hopefully that should get us across the line or at least very close to it ..

[1] https://github.com/cla-assistant/cla-assistant

**Comment by clux** [comment]
I see the [CLA-Assistant is actually used by Deislabs](https://github.com/deislabs/krustlet/blob/main/CONTRIBUTING.md#contributor-license-agreement). Setup is easy, 2 clicks to authorise with github (read perms on user), then accept with name (might have to fill in if missing in user details) as a user/corp.

(I also see that `helm` started out with the CNCF CLA but [moved on to a DCO](https://github.com/helm/helm/pull/4517) (because apparently [not needed after handover](https://github.com/helm/helm/issues/663)) - maybe something to keep in mind)

Presumably, the most important aspects of the CLA is that we retroactively get rights [as required by the CNCF CLA](https://github.com/cncf/cla/blob/master/individual-cla.pdf);
- (2,3) grant of copyright license + patent license for all past contributions
- (4,5) verification that contributors were legally entitled to grant these licenses, and made by them (but with indemnification for them in clause 6)

The last clause (7; method to submit on behalf of 3rd party) is probably not needed unless someone says so in the big issue. But I guess we can include it in the document.

I think we can take these important bits from [CNCF's CLAs](https://github.com/cncf/cla), swap out the definitions of "The Foundation" for [kube-rs owners](https://github.com/orgs/kube-rs/teams/owners) and point ownership to us. That way, we still have something out of this after all this is done if kubernetes end up being less cooperative than we thought (in which case we will [consider using this new organisation as a home instead](https://github.com/kube-rs/kube-rs/issues/586#issuecomment-881543607))

Interestingly, CLA-Assistant seems to have a drop-down for corp/invididual (at least for Deislabs), whereas CNCF has two documents, so not sure if this is easy to reconcile (haven't checked fully yet). But this is probably at the point where I have to ask them.

I don't know if you have any experience with these particular aspects @soenkeliebau? Does this seem like a sensible course of action to you?

**Comment by soenkeliebau** [comment]
I don't think CLA assistant supports serving different versions of the CLA for individuals and legal entities tbh. We tried solving this by defining "you" based on the selection in the dropdown you mentioned in our CLA [1].

That dropdown is something that can be freely defined when setting up the CLA assistant and also used to gather additional information besides that. 

For our case, I think so far we have only gathered individual CLAs via the assistant, all corporate CLAs have been discussed and signed via mail and not the assistant. 

Regarding your questions about the content of the CLA while ianal that sounds sensible to me, however my suggestion would be to discuss this with the relevant people up front who need to accept the donation to ensure you don't have to gather consent twice :)
I believe @brendandburns mentioned this in a comment as well, maybe he can put you in contact with the right people?

[1] https://gist.github.com/eff20055a7b40e1a9932e0b4cbd62f78
[2] https://github.com/cla-assistant/cla-assistant#request-more-information-from-the-cla-signer

**Comment by clux** [comment]
In the interest of not delaying this any further. I am planning on adding this early next week with CLA-Assistant using [CNCF's individual CLA](https://github.com/cncf/cla/blob/master/individual-cla.pdf), but with the following non-legal modifications:

- **removal of mail form starting at paragraph 2, and ending at the E-Mail: _____ line.** Because we only let people sign electronically via CLA-assistant. [Stackable does a similar modification](https://gist.github.com/lfrancke/eff20055a7b40e1a9932e0b4cbd62f78) (although they make other modifications and elaborate that you are electronically signing). Regardless, this is in the header of the document.
- **replace `CNCF` with `kube-rs`** Only used in the header
- **replace `The Cloud Native Computing Foundation (the "Foundation")` with `The kube-rs organisation (the "Organisation")`**
- **replace `The Foundation` with `The Organisation` everywhere**.

(really feels like github ought to standardise something like this in the future, so that people can just read a name like "CNCF CLA")

<details>
<summary>Full Planned CLA</summary>
<div>
Thank you for your interest in the kube-rs project (“kube-rs”) of The kube-rs organisation (the "Organisation"). In order to clarify the intellectual property license granted with Contributions from any person or entity, the Organisation must have a Contributor License Agreement ("CLA") on file that has been signed by each Contributor, indicating agreement to the license terms below. This license is for your protection as a Contributor as well as the protection of kube-rs, the Organisation and its users; it does not change your rights to use your own Contributions for any other purpose.

You accept and agree to the following terms and conditions for Your present and future Contributions submitted to the Organisation. In return, the Organisation shall not use Your Contributions in a way that is contrary to the public benefit or inconsistent with its nonprofit status and bylaws in effect at the time of the Contribution. Except for the license granted herein to the Organisation and recipients of software distributed by the Organisation, You reserve all right, title, and interest in and to Your Contributions.

1. Definitions.

"You" (or "Your") shall mean the copyright owner or legal entity authorized by the copyright owner that is making this Agreement with the Organisation. For legal entities, the entity making a Contribution and all other entities that control, are controlled by, or are under common control with that entity are considered to be a single Contributor. For the purposes of this definition, "control" means (i) the power, direct or indirect, to cause the direction or management of such entity, whether by contract or otherwise, or (ii) ownership of fifty percent (50%) or more of the outstanding shares, or (iii) beneficial ownership of such entity.

"Contribution" shall mean any original work of authorship, including any modifications or additions to an existing work, that is intentionally submitted by You to the Organisation for inclusion in, or documentation of, any of the products owned or managed by the Organisation (the "Work"). For the purposes of this definition, "submitted" means any form of electronic, verbal, or written communication sent to the Organisation or its representatives, including but not limited to communication on electronic mailing lists, source code control systems, and issue tracking systems that are managed by, or on behalf of, the Organisation for the purpose of discussing and improving the Work, but excluding communication that is conspicuously marked or otherwise designated in writing by You as "Not a Contribution."

2. Grant of Copyright License. Subject to the terms and conditions of this Agreement, You hereby grant to the Organisation and to recipients of software distributed by the Organisation a perpetual, worldwide, non­exclusive, no­charge, royalty­free, irrevocable copyright license to reproduce, prepare derivative works of, publicly display, publicly perform, sublicense, and distribute Your Contributions and such derivative works.

3. Grant of Patent License. Subject to the terms and conditions of this Agreement, You hereby grant to the Organisation and to recipients of software distributed by the Organisation a perpetual, worldwide, non­exclusive, no­charge, royalty­free, irrevocable (except as stated in this section) patent license to make, have made, use, offer to sell, sell, import, and otherwise transfer the Work, where such license applies only to those patent claims licensable by You that are necessarily infringed by Your Contribution(s) alone or by combination of Your Contribution(s) with the Work to which such Contribution(s) was submitted. If any entity institutes patent litigation against You or any other entity (including a cross­claim or counterclaim in a lawsuit) alleging that your Contribution, or the Work to which you have contributed, constitutes direct or contributory patent infringement, then any patent licenses granted to that entity under this Agreement for that Contribution or Work shall terminate as of the date such litigation is filed.

4. You represent that you are legally entitled to grant the above license. If your employer(s) has rights to intellectual property that you create that includes your Contributions, you represent that you have received permission to make Contributions on behalf of that employer, that your employer has waived such rights for your Contributions to the Organisation, or that your employer has executed a separate Corporate CLA with the Organisation.

5. You represent that each of Your Contributions is Your original creation (see section 7 for submissions on behalf of others). You represent that Your Contribution submissions include complete details of any third­party license or other restriction (including, but not limited to, related patents and trademarks) of which you are personally aware and which are associated with any part of Your Contributions.

6. You are not expected to provide support for Your Contributions, except to the extent You desire to provide support. You may provide support for free, for a fee, or not at all. Unless required by applicable law or agreed to in writing, You provide Your Contributions on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied, including, without limitation, any warranties or conditions of TITLE, NON­INFRINGEMENT, MERCHANTABILITY, or FITNESS FOR A PARTICULAR PURPOSE.

7. Should You wish to submit work that is not Your original creation, You may submit it to the Organisation separately from any Contribution, identifying the complete details of its source and of any license or other restriction (including, but not limited to, related patents, trademarks, and license agreements) of which you are personally aware, and conspicuously marking the work as "Submitted on behalf of a third­party: [named here]".

8. You agree to notify the Organisation of any facts or circumstances of which you become aware that would make these representations inaccurate in any respect.
</div>
</details>

and

<details>
<summary>Markdown diff with CNCF CLA</summary>

```diff
diff --git cla-individual.md cla-individual.md
index 8f00ff8..005e5af 100644
--- cla-individual.md
+++ cla-individual.md
@@ -1,23 +1,23 @@
-Thank you for your interest in the Cloud Native Computing Foundation project (“CNCF”) of The Linux Foundation (the "Foundation"). In order to clarify the intellectual property license granted with Contributions from any person or entity, the Foundation must have a Contributor License Agreement ("CLA") on file that has been signed by each Contributor, indicating agreement to the license terms below. This license is for your protection as a Contributor as well as the protection of CNCF, the Foundation and its users; it does not change your rights to use your own Contributions for any other purpose.
+Thank you for your interest in the kube-rs project (“kube-rs”) of The kube-rs organisation (the "Organisation"). In order to clarify the intellectual property license granted with Contributions from any person or entity, the Organisation must have a Contributor License Agreement ("CLA") on file that has been signed by each Contributor, indicating agreement to the license terms below. This license is for your protection as a Contributor as well as the protection of kube-rs, the Organisation and its users; it does not change your rights to use your own Contributions for any other purpose.
 
-You accept and agree to the following terms and conditions for Your present and future Contributions submitted to the Foundation. In return, the Foundation shall not use Your Contributions in a way that is contrary to the public benefit or inconsistent with its nonprofit status and bylaws in effect at the time of the Contribution. Except for the license granted herein to the Foundation and recipients of software distributed by the Foundation, You reserve all right, title, and interest in and to Your Contributions.
+You accept and agree to the following terms and conditions for Your present and future Contributions submitted to the Organisation. In return, the Organisation shall not use Your Contributions in a way that is contrary to the public benefit or inconsistent with its nonprofit status and bylaws in effect at the time of the Contribution. Except for the license granted herein to the Organisation and recipients of software distributed by the Organisation, You reserve all right, title, and interest in and to Your Contributions.
 
 1. Definitions.
 
-"You" (or "Your") shall mean the copyright owner or legal entity authorized by the copyright owner that is making this Agreement with the Foundation. For legal entities, the entity making a Contribution and all other entities that control, are controlled by, or are under common control with that entity are considered to be a single Contributor. For the purposes of this definition, "control" means (i) the power, direct or indirect, to cause the direction or management of such entity, whether by contract or otherwise, or (ii) ownership of fifty percent (50%) or more of the outstanding shares, or (iii) beneficial ownership of such entity.
+"You" (or "Your") shall mean the copyright owner or legal entity authorized by the copyright owner that is making this Agreement with the Organisation. For legal entities, the entity making a Contribution and all other entities that control, are controlled by, or are under common control with that entity are considered to be a single Contributor. For the purposes of this definition, "control" means (i) the power, direct or indirect, to cause the direction or management of such entity, whether by contract or otherwise, or (ii) ownership of fifty percent (50%) or more of the outstanding shares, or (iii) beneficial ownership of such entity.
 
-"Contribution" shall mean any original work of authorship, including any modifications or additions to an existing work, that is intentionally submitted by You to the Foundation for inclusion in, or documentation of, any of the products owned or managed by the Foundation (the "Work"). For the purposes of this definition, "submitted" means any form of electronic, verbal, or written communication sent to the Foundation or its representatives, including but not limited to communication on electronic mailing lists, source code control systems, and issue tracking systems that are managed by, or on behalf of, the Foundation for the purpose of discussing and improving the Work, but excluding communication that is conspicuously marked or otherwise designated in writing by You as "Not a Contribution."
+"Contribution" shall mean any original work of authorship, including any modifications or additions to an existing work, that is intentionally submitted by You to the Organisation for inclusion in, or documentation of, any of the products owned or managed by the Organisation (the "Work"). For the purposes of this definition, "submitted" means any form of electronic, verbal, or written communication sent to the Organisation or its representatives, including but not limited to communication on electronic mailing lists, source code control systems, and issue tracking systems that are managed by, or on behalf of, the Organisation for the purpose of discussing and improving the Work, but excluding communication that is conspicuously marked or otherwise designated in writing by You as "Not a Contribution."
 
-2. Grant of Copyright License. Subject to the terms and conditions of this Agreement, You hereby grant to the Foundation and to recipients of software distributed by the Foundation a perpetual, worldwide, non­exclusive, no­charge, royalty­free, irrevocable copyright license to reproduce, prepare derivative works of, publicly display, publicly perform, sublicense, and distribute Your Contributions and such derivative works.
+2. Grant of Copyright License. Subject to the terms and conditions of this Agreement, You hereby grant to the Organisation and to recipients of software distributed by the Organisation a perpetual, worldwide, non­exclusive, no­charge, royalty­free, irrevocable copyright license to reproduce, prepare derivative works of, publicly display, publicly perform, sublicense, and distribute Your Contributions and such derivative works.
 
-3. Grant of Patent License. Subject to the terms and conditions of this Agreement, You hereby grant to the Foundation and to recipients of software distributed by the Foundation a perpetual, worldwide, non­exclusive, no­charge, royalty­free, irrevocable (except as stated in this section) patent license to make, have made, use, offer to sell, sell, import, and otherwise transfer the Work, where such license applies only to those patent claims licensable by You that are necessarily infringed by Your Contribution(s) alone or by combination of Your Contribution(s) with the Work to which such Contribution(s) was submitted. If any entity institutes patent litigation against You or any other entity (including a cross­claim or counterclaim in a lawsuit) alleging that your Contribution, or the Work to which you have contributed, constitutes direct or contributory patent infringement, then any patent licenses granted to that entity under this Agreement for that Contribution or Work shall terminate as of the date such litigation is filed.
+3. Grant of Patent License. Subject to the terms and conditions of this Agreement, You hereby grant to the Organisation and to recipients of software distributed by the Organisation a perpetual, worldwide, non­exclusive, no­charge, royalty­free, irrevocable (except as stated in this section) patent license to make, have made, use, offer to sell, sell, import, and otherwise transfer the Work, where such license applies only to those patent claims licensable by You that are necessarily infringed by Your Contribution(s) alone or by combination of Your Contribution(s) with the Work to which such Contribution(s) was submitted. If any entity institutes patent litigation against You or any other entity (including a cross­claim or counterclaim in a lawsuit) alleging that your Contribution, or the Work to which you have contributed, constitutes direct or contributory patent infringement, then any patent licenses granted to that entity under this Agreement for that Contribution or Work shall terminate as of the date such litigation is filed.
 
-4. You represent that you are legally entitled to grant the above license. If your employer(s) has rights to intellectual property that you create that includes your Contributions, you represent that you have received permission to make Contributions on behalf of that employer, that your employer has waived such rights for your Contributions to the Foundation, or that your employer has executed a separate Corporate CLA with the Foundation.
+4. You represent that you are legally entitled to grant the above license. If your employer(s) has rights to intellectual property that you create that includes your Contributions, you represent that you have received permission to make Contributions on behalf of that employer, that your employer has waived such rights for your Contributions to the Organisation, or that your employer has executed a separate Corporate CLA with the Organisation.
 
 5. You represent that each of Your Contributions is Your original creation (see section 7 for submissions on behalf of others). You represent that Your Contribution submissions include complete details of any third­party license or other restriction (including, but not limited to, related patents and trademarks) of which you are personally aware and which are associated with any part of Your Contributions.
 
 6. You are not expected to provide support for Your Contributions, except to the extent You desire to provide support. You may provide support for free, for a fee, or not at all. Unless required by applicable law or agreed to in writing, You provide Your Contributions on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied, including, without limitation, any warranties or conditions of TITLE, NON­INFRINGEMENT, MERCHANTABILITY, or FITNESS FOR A PARTICULAR PURPOSE.
 
-7. Should You wish to submit work that is not Your original creation, You may submit it to the Foundation separately from any Contribution, identifying the complete details of its source and of any license or other restriction (including, but not limited to, related patents, trademarks, and license agreements) of which you are personally aware, and conspicuously marking the work as "Submitted on behalf of a third­party: [named here]".
+7. Should You wish to submit work that is not Your original creation, You may submit it to the Organisation separately from any Contribution, identifying the complete details of its source and of any license or other restriction (including, but not limited to, related patents, trademarks, and license agreements) of which you are personally aware, and conspicuously marking the work as "Submitted on behalf of a third­party: [named here]".
 
-8. You agree to notify the Foundation of any facts or circumstances of which you become aware that would make these representations inaccurate in any respect.
+8. You agree to notify the Organisation of any facts or circumstances of which you become aware that would make these representations inaccurate in any respect.

```

</details>

**Comment by clux** [comment]
Although might also need to make a similar change to @soenkeliebau 's suggestion on the CLA-assistant to define "You" based on a dropdown selection. Might have to try it out on a test project first.

**Comment by clux** [comment]
CLA gist here: https://gist.github.com/clux/a4e349e729af96faff044c753edbbdb7

- Converted text to have markdown headers like [stackable's one](https://gist.github.com/lfrancke/eff20055a7b40e1a9932e0b4cbd62f78) and used their metadata.
- Listed CNCF CLA clause 4,5 and 7 under a `## 4. Representations` header (didn't know what else to summarise them as, and stackable rewrites those bits).

**Comment by teozkr** [comment]
One thing I'm a bit worried about is that kube-rs is not a legal person (natural person, corporation, non-profit, and so on). It might be easier if it's addressed to you (@clux) personally instead?

**Comment by clux** [comment]
Yeah, that's a fair point. It looks legally easier to pin it on me temporarily, although the legalese feels pretty heavy handed with that template though :D

> Thank you for your interest in the kube-rs project (“kube-rs”) by Eirik `clux` Albrigtsen (the "Owner").

**Comment by clux** [comment]
Updated with [me as the legal pin](https://gist.github.com/clux/a4e349e729af96faff044c753edbbdb7). Also removed the corresponding guarantee that I will "adhere to non-profit bylaws at the time of the contribution" because it doesn't make sense for an individual. Left the "good faith" sentence though:

> in return, the Owner shall not use Your Contributions in a way that is contrary to the public benefit

**Comment by clux** [comment]
In an unexpected turn of events, we can probably drop our CLA idea for a simple DCO based on [CNCF Chris's comments](https://github.com/kube-rs/kube-rs/issues/584#issuecomment-892012375) (plus a few comments above) because we use Apache2 out of the box. (A [DCO is still necessary](https://github.com/cncf/foundation/issues/130))

The [guidelines in the official doucment on CNCF](https://github.com/cncf/foundation/blob/master/copyright-notices.md#ownership-of-copyrights-in-cncf-project-contributions) are a lot more lightweight:

- no copyright headers anywhere, just a generic Copyright The Kube-rs Authors (i need to typo fix that from the license file)
- original authors keep their copyrights

AFAIKT the only thing we lose out on is the ability to relicense our code, and if i never have to deal with the legal aspect again, then i'm good :-)

PLAN:
- write a contributors guide
- install the [DCO app](https://github.com/apps/dco) in the org
- write a file for [CERTIFICATE_OF_ORIGIN](https://developercertificate.org/) (if it is required with the DCO app)
- update LICENSE line with authors to match req and set the year correctly to 2018 (when we actually started)
