### ISSUE TITLE
standardise known issues in our releases

### ISSUE THREAD

**Issue by clux** [kube-rs/kube-rs#601]
We added a `known issues` to our releases in 0.57: See https://github.com/kube-rs/kube-rs/releases/tag/0.58.0.

I'd like to automate that so that the `prerelease.sh` script does a query up to github and enumerates bug issues with some `critical` label.

I know that #581 probably needed more of a notice than what was given, but at least if we stick with a convention, people know where to look. Raising this because at least many of the krustlet guys (incl @thomastaylor312 ) was unaware of the sketchiness of our last releases in terms of serialisation. 

If there are any better ways of doing this type of **notices**, then input is welcome.
This should possibly have been a security notice. Maybe it's worth just trying to adopt kubernetes' security notice style. Whatever that entails.

**Comment by thomastaylor312** [comment]
FWIW, it wasn't as much of a security problem for us as we should have more thoroughly read the known issues section. But I do think having a standardized way of this would be helpful as usage continues to grow!

**Comment by clux** [comment]
Have added a [critical label](https://github.com/kube-rs/kube-rs/labels/critical) for this purpose. Will close this via a bit of curl magic from the release script to append the title and link to any `critical` issues.
