### ISSUE TITLE
Fails to compile against k8s-openapi with the 1_22 feature

### ISSUE THREAD

**Issue by lfrancke** [kube-rs/kube-rs#621]
```
error[E0433]: failed to resolve: could not find `v1beta1` in `apiexts`
  --> /home/lars/.cargo/registry/src/github.com-1ecc6299db9ec823/kube-core-0.59.0/src/crd.rs:33:37
   |
33 |         fn crd() -> super::apiexts::v1beta1::CustomResourceDefinition;
   |                                     ^^^^^^^ could not find `v1beta1` in `apiexts`

```

https://kubernetes.io/blog/2021/07/14/upcoming-changes-in-kubernetes-1-22/#api-changes
The `v1beta1` thing as been removed in 1.22.

**Comment by clux** [comment]
Ah. Right. Yup, that probably needs a feature workaround. Probably one of:

- gated on a v1_22 feature (but don't really want to introduce version features here)
- gated on the k8s-openapi feature (but don't think we can gate on features in other crates)
- gated behind a `deprecated_apis` feature

The last lets users explicitly opt in while they exist in `k8s-openapi`, without us having to track versions

**Comment by lfrancke** [comment]
Option two would be the "best" in terms of usability but if that doesn't work I'm in favor of the last option as well.

**Comment by teozkr** [comment]
AFAIK we can't see dependency features (and it would have the same issue
where we need to maintain tables of which k8s versions support which
features.

I'd consider adding a `deprecated-crd-v1beta1` feature. That way:

1. Users get a clearish full error when the feature is fully removed
2. We don't have to care about which k8s removes or deprecates what
3. We can support multiple features at different stages of their
deprecation cycles

**Comment by clux** [comment]
Started a PR for this in #622. Using the longer name feature as suggested, completely agree with that argument.
