### ISSUE TITLE
Need to set content-type for certain cluster types

### ISSUE THREAD

**Issue by clux** [kube-rs/kube-rs#626]
From reports on discord, https://agones.dev/site/ does require the content-type header set, and we are not setting it.

- ~~We probably need to incorporate this into a new layer or our base layer.~~
- ~~We might need to make this configurable in the future to handle protobufs~~

But we can work around this with `tower-http` [middleware](https://docs.rs/tower-http/0.1.1/tower_http/set_header/struct.SetRequestHeaderLayer.html):

```rust
async fn build_kube_client(namespace: &str) -> Result<Client, AgonesError> {
    let config = Config::infer().await?;
    let https = config.rustls_https_connector()?;

    let service = tower::ServiceBuilder::new()
        // required setup for `kube::Client` to work
        .layer(config.base_uri_layer())
        .option_layer(config.auth_layer()?)
        // kube doesn't set `content-type: application/json` which agones requires
        .layer(SetRequestHeaderLayer::<_, Body>::if_not_present(
            http::header::CONTENT_TYPE,
            http::HeaderValue::from_static("application/json"),
        ))
        .service(hyper::Client::builder().build(https));

    Ok(Client::new(service, namespace))
}
```

Via [discord](https://discord.com/channels/500028886025895936/685161813675212899/880436854246215801)

**Comment by teozkr** [comment]
Seems like this would belong in our `Request` creation code, since the content-type already has semantic significance for patches?

**Comment by clux** [comment]
> Seems like this would belong in our `Request` creation code, since the content-type already has semantic significance for patches?

That is true! We can tie it to our `Request` by using the setters on [http::Request](https://docs.rs/http/0.2.4/http/request/struct.Request.html) (instead of hard-overriding it with layers) and then we tie the content type to the http api explicitly.

**Comment by kazk** [comment]
Opened #627
