### ISSUE TITLE
Add generic ways to wait for conditions and deletions

### ISSUE THREAD

**Issue by clux** [kube-rs/kube-rs#632]
From kubectl's [wait module](https://pkg.go.dev/k8s.io/kubectl@v0.22.1/pkg/cmd/wait) (see [source](https://github.com/kubernetes/kubectl/blob/v0.22.1/pkg/cmd/wait/wait.go)) there are a couple of helpers there that we could have almost direct translations of, and I think they would be very useful:

- `isDeleted(watch.Event)`

The dumbest and easiest one to do. Could be a dumb `impl WatchEvent { fn is_deleted(&self) }`

- `isDeleted(*resource.Info, *WaitOptions)`

Basically, this does what #631 is doing, but in a more building-block-y manner. We could take that and still export the method from #631, but waiting for deletion I think is useful to more than finalizers.

I think this could just be a new thing in `kube_runtime` like `waiter` or maybe just `Wait` struct (since we have to many -er suffixed things and waiter could also be a servant), and it could be constructed with many different ways. One could be `Wait<K>::for_delete(&WaitParams)`, and another could be for ...:

- `isConditionMet(*resource.Info, *WaitOptions)`
 
This is one I would really want. It's letting you do  what `kubectl wait` lets you do. I.e. wait for `.status.conditions` to reach a certain condition. `WaitParams` would either have to encompass this or, we have something like `Wait<K>::for_condition(conditionKey, conditionValue, WaitOptions)`. In either case we need to handle timeouts.

The wait module also seems to deal with `observedGeneration` plus a bunch of stuff that i suspect are "go problems", but this probably needs a bit of care.

**Comment by teozkr** [comment]
So I started sketching on breaking out a `wait` from #631 (`is_deleted` wouldn't be quite so simple, because it needs to validate `uid`, but that's a separate concern anyway..): https://github.com/teozkr/kube-rs/commit/c029b8d2d33dd317f36dcc06d44afa6dea781342

However, this still makes a bunch of assumptions (some of which make it more ergonomic for the deletion use-case, but make it less useful in the general case). For example:

1. We don't return anything
2. `cond` is assumed to be infallible
3. `cond` is assumed to be (near-)instant
4. There is no support for resyncing on errors

**Comment by teozkr** [comment]
So I think a core realization here is that we need a more ergonomic way to watch a single object: https://github.com/teozkr/kube-rs/commit/af92093f399d7fbbadd1d2b4fac0fdcc9a7afa25

This lets us break out the event flattening, without needing to enforce any of these assumptions.

Once we have that, `await_condition` becomes trivial, and little more than an encoding of these assumptions on top of `try_take_while`. We could generalize that as a `TryStream::try_take_first()` or similar.

**Comment by clux** [comment]
Yeah, I think that's a good way forward. Maybe the current `watcher` interface is more geared towards the `reflector` integration than the most ergonomic human user standpoint.

I do feel that such a watch should probably pass on all events so that users can decide (even if that means they get some duplicates), because if they are waiting for conditions or such things, then doing duplicate checks feels better than catching errors there. Unless there is some other problem with that that I'm missing.

**Comment by teozkr** [comment]
> I do feel that such a watch should probably pass on all events so that users can decide (even if that means they get some duplicates on resets)

Absolutely, and the proposed `watch_object` does that. What it does not do is try to group events atomically (because there can at most be one matching object anyway).

**Comment by clux** [comment]
it does look like it bails out on a relist though from this line:

```rust
Event::Restarted(objs) if objs.len() > 1 => TooManyObjects.fail(),
```

i meant that the result stream should probably have `objs` injected into the output as well.

**Comment by teozkr** [comment]
Since we filter on names, which are unique, that should only ever happen if the K8s apiserver is broken (in which case our API would be leading to broken assumptions anyway).

**Comment by teozkr** [comment]
We could add `objs` to the `TooManyObjects` error object I guess, but this is definitely still an error case.

**Comment by clux** [comment]
> Since we filter on names, which are unique, that should only ever happen if the K8s apiserver is broken and either accepting duplicate objects with the same name or not applying the filter properly (in which case our API would lead to broken assumptions anyway).

Ahhh. OK. It's already filtered so the relist would only have one element. Sorry. That makes sense to me now.
