### ISSUE TITLE
Non-exhustive on Patch struct makes writing safe code around it impossible

### ISSUE THREAD

**Issue by danrspencer** [kube-rs/kube-rs#705]
https://github.com/kube-rs/kube-rs/blob/120d0001ce58eb18ac59d2a9da1bf8514bc8058c/kube-core/src/params.rs#L198

Is there a reason that `#[non-exhaustive]` is on the the Patch struct? It makes safely handling patch variants in code far more difficult, if not impossible.

Instead of being able to write:

```
match patch {
            Patch::Apply(_) => do_thing(),
            Patch::Json(_) => do_thing(),
            Patch::Merge(_) => do_thing(),
            Patch::Strategic(_) => do_thing()
}
```

I have to write something like:

```
match patch {
            Patch::Apply(_) => do_thing(),
            Patch::Json(_) => do_thing(),
            Patch::Merge(_) => do_thing(),
            Patch::Strategic(_) => do_thing(),
            _ => panic!() // Or some other fudge 
}
```

If a new patch variant gets added and we upgrade the library we won't know at compile time, we'll only find out about the unhandled patch type at runtime.

**Comment by teozkr** [comment]
`Patch::Json` is only available when the `jsonpatch` feature is enabled, so without this enabling the `jsonpatch` feature would break any library trying to pattern-match on `Patch` without it.

**Comment by danrspencer** [comment]
It feels like that's just traded one problem for another? We've hit this problem a few times now (I can't remember the specific use cases for each) when working with patches that we just can't write future safe code around it. 

Perhaps a different struct could be offered which contained the `jsonpatch` type vs the one that doesn't. I realise that's probably difficult to implement now on an already public API; but I feel there has to be a better solution that removing the ability to have compile time safety when matching on this struct?

**Comment by teozkr** [comment]
Long-term I suspect your only safe bet would be to build your own `Patch` enum, and only convert that into a kube `Patch` right before submitting into to `Api::patch`.

That said, it's hard to say much more without knowing what your use-case is?

**Comment by danrspencer** [comment]
The use case is anywhere in the code you have to match `Patch`. Having it be `#[non-exhaustive]` means it's essentially impossible to safely write code around that. We do already wrap Patch to add other useful functionality like `PartialEq`, so maybe we do need to just extend that further. But I do think having a non-exhaustive struct as part of your public interface is just forcing people to write unsafe code, or reimplement the `Patch` struct themselves.

**Comment by clux** [comment]
I guess the usual non exhaustive error enum argument here maybe falls apart a bit if apps want to handle all kubernetes patch features and suddenly find through `kube` upgrades that there's a new one they don't support.

It is a relatively minor point for this enum (if kubernetes added new patch mode at this point, it would probably be big news), and [`std::matches`](https://doc.rust-lang.org/std/macro.matches.html) minimizes the needs for most `PartialEq` shenanigans (i think?).

The feature point is slightly annoying, but if users are matching on `Patch` and swapping features, at least they'll get to know while developing, so probably not a big deal?

Imo, it's OK to remove the  `#[non_exhaustive]` mark here. The one potential minor breaking change it would cause (if kubernetes made a new patch one) is probably something we could allow in our > 1.0 version policy anyway.

**Comment by danrspencer** [comment]
`PartialEq` we mostly use in tests; often we don't want to know about the actual contents of a patch in a some tests, we just want to check it matches an expected patch. But I don't want to derail the discussion and I'm happy having to wrap `Patch` to add that ourselves.

I think removing `#[non_exhaustive]` may actually improve the feature swapping. If `jsonpatch` is enabled where it wasn't previously, and I had code handling different types of patches, I would want the compiler to tell me my code no longer covers all of the possible cases.

**Comment by teozkr** [comment]
Ultimately, it sounds like a fundamental disagreement where you'd like to bypass `#[non_exhaustive]`, acknowledging that this means that you're trading away semver compatibility and the normally-additive nature of cargo features. It is actually possible to do this for any `#[non_exhaustive]` pattern, by ensuring that linking fails if rustc is unable to eliminate the branch: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=768fc79dd8033b9ec0217b23093399b7

Yes, it's ugly and not very obvious, but personally I'm not comfortable encouraging this kind of behaviour along the "happy path".

> The use case is anywhere in the code you have to match `Patch`.

That's a proposed (part of a) solution, not the root problem that you're trying to solve.

> But I do think having a non-exhaustive struct as part of your public interface is just forcing people to write unsafe code

This is about *fallible* code, not memory safety. Even in the worst case, while panicking is rarely a desirable result, it will *not* segfault or open you up to another heartbleed (assuming that your panic handler isn't broken of course, but that's basically a requirement regardless).

**Comment by teozkr** [comment]
> I think removing #[non_exhaustive] may actually improve the feature swapping. If jsonpatch is enabled where it wasn't previously, and I had code handling different types of patches, I would want the compiler to tell me my code no longer covers all of the possible cases.

That's not of much help if that pattern matching is going on in some third-party library. At best, you now need to keep their feature set in sync with kube's, manually.

**Comment by teozkr** [comment]
As for the rest, I do think it would make sense to derive `PartialEq`, at least.

**Comment by danrspencer** [comment]
If some additional derives were added to the `Patch` struct I think that would solve most of our painful cases. Now I think back to last time we encountered this it was when trying to impl a standard function (unfortunately I can't remember which one), which makes the incomplete matching especially painful because you can't simply return a `Result` if the trait doesn't expect one.

We're currently mostly extending `Patch` to add `PartialEq ` and `Debug`.

> That's not of much help if that pattern matching is going on in some third-party library. At best, you now need to keep their feature set in sync with kube's, manually.

That's a fair point and one I hadn't considered.

**Comment by clux** [comment]
Added `PartialEq` + `Clone` on `Patch`. We already had `Debug`. Hopefully that makes it a bit better.

**Comment by danrspencer** [comment]
@clux That really helps, cheers. I also remember the original problem that had me pulling my hair out now:

```
impl Clone for KubePatch {
    fn clone(&self) -> Self {
        match &self.0 {
            Patch::Apply(value) => KubePatch(Patch::Apply(value.clone())),
            Patch::Json(value) => KubePatch(Patch::Json(value.clone())),
            Patch::Merge(value) => KubePatch(Patch::Merge(value.clone())),
            Patch::Strategic(value) => KubePatch(Patch::Strategic(value.clone())),
            _ => panic!()
        }
    }
}
```

It's essentially impossible to write a future safe clone method since it's not already derived. Having it added directly on to `Patch` will solve this.
