### ISSUE TITLE
Export functionality to load Kubeconfig from text

### ISSUE THREAD

**Issue by imp** [kube-rs/kube-rs#718]
### Would you like to work on this feature?

yes

### What problem are you trying to solve?

Besides loading `Kubeconfig` from files or env var, there are situations where you have plain text coming from somewhere else, rather than a file. For example, when working with ClusterAPI the `Kubeconfig` is stored in the secret. It might be a good idea to provide an `impl FromStr for Kubeconfig` and let every other higher-level functions just use it.

### Describe the solution you'd like

```
impl FromStr for Kubeconfig
```

### Describe alternatives you've considered

An alternative would be to write just a free-standing function or just implement it (really two-liners) in your own code.

### Documentation, Adoption, Migration Strategy

Well, the use should be straightforward, via [parse()](https://doc.rust-lang.org/std/primitive.str.html#method.parse) method

### Target crate for feature

kube-client

**Comment by kazk** [comment]
Like this?
```rust
let config: Kubeconfig = serde_yaml::from_str(secret).unwrap();
```

**Comment by clux** [comment]
I guess it makes sense to expose something that does what `Kubeconfig::read_from` does in the absense of a file path now that we handle multi-doc kubeconfigs. Plus it potentially allows users to not having to manually specify `serde_yaml` in their cargo toml if this is their only use case.

I'm :+1: . Happy to review a PR.
