### ISSUE TITLE
Regression of applier build times in Rust 1.57

### ISSUE THREAD

**Issue by teozkr** [kube-rs/kube-rs#746]
### Current and expected behavior

# 1.57 behaviour

1. Check out https://gitlab.com/teozkr/repros/-/tree/kube/rs1.57-compile-regression.
2. `rustup update 1.57.0`
3. `cargo +1.57.0 build`
4. Note that the full build gets stuck for several minutes on `rs157-compile-regression(bin)`
5. `touch src/main.rs`
6. `cargo +1.57.0 build`
7. Note that the incremental build takes ~40s (on my machine, scale to yours)

# 1.56 behaviour

1. `rustup update 1.56.1`
2. `cargo +1.56.1 build`
3. Note that the full build completes in ~30s (on my machine, scale to yours)
4. `touch src/main.rs`
5. `cargo +1.56.1 build`
6. Note that the incremental build takes ~3s (on my machine, scale to yours)

### Possible solution

More of a workaround, but boxing `queue`:

```diff
diff --git a/src/main.rs b/src/main.rs
index a306bba..6e08d03 100644
--- a/src/main.rs
+++ b/src/main.rs
@@ -25,7 +25,8 @@ async fn main() {
                 stream::empty::<Result<watcher::Event<ConfigMap>, watcher::Error>>(),
             )),
             (),
-        ),
+        )
+        .boxed(),
     )
     .boxed()
     .for_each(|_| async {})
```

brings the incremental rebuild time down to ~4s.

### Environment

Arch Linux
Rustc 1.57 (bad), 1.56.1 (good)
K8s cluster is irrelevant since this is a build issue

### Configuration and features

```toml
kube = { version = "0.64.0", features = ["runtime"] }
k8s-openapi = { version = "0.13.1", features = ["v1_22"] }
```

### Affected crates

kube-runtime

### Would you like to work on fixing this bug?

yes

**Comment by teozkr** [comment]
Curiously, this only seems to happen for the pattern `applier(..., trigger_self(try_flatten_applied(reflector(...))))`. Removing any of those steps, or erasing to a trait object (with `StreamExt::boxed`) seems to step around the issue.

**Comment by clux** [comment]
Good spot. Confirming it happens on mine as well.

```sh
$ touch src/main.rs 
$ time cargo +1.57.0 build
   Compiling rs157-compile-regression v0.1.0 (/home/clux/repos/repros/repros)
    Finished dev [unoptimized + debuginfo] target(s) in 1m 18s

real	1m18.798s
user	1m12.865s
sys	0m5.807s
```

then clean and after building once:

```sh
$ touch src/main.rs 
$ time cargo +1.56.1 build
   Compiling rs157-compile-regression v0.1.0 (/home/clux/repos/repros/repros)
    Finished dev [unoptimized + debuginfo] target(s) in 3.12s

real	0m3.158s
user	0m2.700s
sys	0m0.458s
```

Dramatic difference.

**Comment by teozkr** [comment]
I can reproduce this with just `futures`, so this seems more like a rustc issue. Filed https://github.com/rust-lang/rust/issues/91598.

**Comment by clux** [comment]
This is is presumably no longer an issue with the fix getting into stable. Are you OK with bumping the msrv from this point on?

**Comment by teozkr** [comment]
Happy to close this and unblock the MSRV, I'm back on stable since 1.59.
