### ISSUE TITLE
fortification: preventing secret leaks

### ISSUE THREAD

**Issue by clux** [kube-rs/kube-rs#751]
### What problem are you trying to solve?

It's possible to log `Kubeconfig`, and `Config` with `Debug` - which looks like it will just log all secret information by default.
I want to make this slightly harder to do. Similarly in request parameters that may have access to them.

### Describe the solution you'd like

A practice I've seen around is to use:

- [secrecy crate](https://docs.rs/secrecy/0.8.0/secrecy/) to wrap the sensitive credentials
- [tower_http::sensitive_headers](https://docs.rs/tower-http/latest/tower_http/sensitive_headers/index.html) to mark access creds as [sensitive](https://docs.rs/http/latest/http/header/struct.HeaderValue.html#method.set_sensitive)

The first can be used in in the `Config`, `Kubeconfig` to help avoiding secrets these being logged (unless explicitly requested via `Secret::expose_secret`).

The second may be helpful, if it fits into the layer stack, not sure about it.

### Describe alternatives you've considered

Removing Debug

### Documentation, Adoption, Migration Strategy

Might be considered a breaking change to the `Kubeconfig` or `Config`, but can be documented, and it is very light.

### Target crate for feature

kube-client

---

- [x] Request headers (https://github.com/kube-rs/kube-rs/issues/751#issuecomment-989157924)
- [x] `AuthInfo` password (#766)
- [x] `AuthInfo` token (#766)
- [x] `AuthInfo` `client_key_data`
  - [x] Copied to `Config` `identity_pem` as well. Cleaned up in #771.

**Comment by kazk** [comment]
Headers should be marked as sensitive already.

Basic/Bearer:

https://github.com/kube-rs/kube-rs/blob/6b23251c9c39097e9a950a7059e39c39755d1b6a/kube-client/src/client/config_ext.rs#L172-L177

Refreshable Token with exec:
https://github.com/kube-rs/kube-rs/blob/303a000bf7eadaad4d3a6ddbf3030d15b4daa193/kube-client/src/client/auth/mod.rs#L126-L128

Refreshable Token with OAuth:
https://github.com/kube-rs/kube-rs/blob/303a000bf7eadaad4d3a6ddbf3030d15b4daa193/kube-client/src/client/auth/mod.rs#L136-L138

**Comment by clux** [comment]
Double checking in [`file_config`](https://github.com/kube-rs/kube-rs/blob/447dad05c1ec5405708827fb345ad2d5c3a8242c/kube-client/src/config/file_config.rs#L142-L207) looks all fortified to me now.

We must have forgotten to close this :smile:
