### ISSUE TITLE
changelog improvements

### ISSUE THREAD

**Issue by clux** [kube-rs/kube-rs#754]
### Current and expected behavior

Current changelog generator is basically my homebrew thing on top of manually a manually maintained file.

The automation is basically; [this script during release process](https://github.com/kube-rs/kube-rs/blob/master/scripts/release-pre.sh#L4-L16), and [this script to put that into a github release](https://github.com/kube-rs/kube-rs/blob/master/scripts/release-gh.sh).

This has several problems:

- [generated links are now wrong](https://github.com/kube-rs/kube-rs/releases) (`/issues` vs `/pull`) used to work on `/issues` always, but have stopped working
- the release does attribute the people who made the release (see [kopium autogenerate inside github ui](https://github.com/kube-rs/kopium/releases/tag/v0.4.0))

Would like to improve this so links are working, have less manual work on maintaining this file, and better user attribution for changes.

### Possible solution

Use another off the shelf generator or use the github one. ~~The github one is __slightly annoying__ because I think the release email is sent when the release is created and the UI press to generate a body happens after.~~(EDIT: this can be changged). But on the other hand, the github autogenerated one is actually really nice looking and simple. Avatars of contributors for the release included.

But maybe we can investigate a bit to do more improvements. I kind of would like to not have to maintain so much of this file by default. If we were consistent with renaming PRs to what they would show up as in the CHANGELOG, maybe that would be a better convention for the 90% use case? I quite like the [thanos release categorisation](https://github.com/thanos-io/thanos/releases/tag/v0.24.0-rc.1)

Maybe we could have a label to indicate fixes/breaking changes. But this makes it hard to actually communicate WHAT broke.. so maybe not.

Possible tools:
- https://github.com/marketplace/actions/release-please-action
- https://github.com/marketplace/actions/release-drafter

**Comment by kazk** [comment]
For some NPM packages and some of our apps, I've been using [release-drafter](https://github.com/marketplace/actions/release-drafter) with [multi-labeler](https://github.com/marketplace/actions/multi-labeler) (to label PRs automatically based on some rules).

---

I also want the changelog to have a more consistent format, grouping changes by kind/severity. Maybe https://keepachangelog.com/en/1.0.0/ .

**Comment by clux** [comment]
I noticed that github built in generator is a lot better than i thought it was.
my original complaint about it generating after the email has been sent does not have to be true ([i was just using the wrong action to do it](https://github.com/kube-rs/kopium/issues/26)):

`softprops/action-gh-release` can set `generate_release_notes: true` to hook into it.

Github's automated release log does have some [very sensible github-oriented configuration features](https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes#configuration-options). It looks very similar to what release-drafter does (but haven't looked in detail at either system). I am going to be experimenting with it a bit in `kopium` first (since it doesn't manually maintain a `CHANGELOG`).

---

I would like a grouping setup as well (mostly because at this point it gets kind of jarring to read "BREAKING" within the changelog everywhere on half the lines - i'd rather just have a `modified` section). Both [release-drafter](https://github.com/marketplace/actions/release-drafter#categorize-pull-requests) and github can natively categorise.

The question I guess is; if we tweak autogeneration - by taking advantage of labels (to filter and categorise), and us renaming PRs - so that we get really good release notes for free - why would we manually maintain the CHANGELOG?

Maybe we just generate the CHANGELOG from the generated release notes and add an extra section about migration when necessary? That's generally what we have anyway. Maybe some support for a few extra lines of elaboration here and there. WDYT?

**Comment by kazk** [comment]
GitHub's generator is much better than what I thought. I didn't realize it supported grouping by labels. [softprops/action-gh-release](https://github.com/softprops/action-gh-release) looks great too.

> The question I guess is; if we tweak autogeneration - by taking advantage of labels (to filter and categorise), and us renaming PRs - so that we get really good release notes for free - why would we manually maintain the CHANGELOG?

Yeah, it's nice to have them generated and organized automatically. Using PR titles as changelog entries has a nice side effect of encouraging better PRs with clear titles, and limited scope too.

I think we should definitely look into them.

---

#### Current Process

0. optionally dry run `cargo release` to confirm the changes applied before publish (step 1 without publish)
1. run `cargo release minor --execute`
  a. bumps versions in `Cargo.toml` (with shared version)
  b. updates README
  c. updates CHANGELOG (move unreleased under the version)
  d. commit the changes
  e. publish crates in order
2. `git tag && git push && git push --tags` after release succeeds
3. On tag push, GitHub Release is created by GitHub Action with a body extracted from the latest version on CHANGELOG

#### Current Process + Generator

If we use GitHub's generator and stopped manually updating CHANGELOG:

0. optionally dry run `cargo release` to confirm the changes applied before publish (step 1 without publish)
1. run `cargo release minor --execute`
  a. bumps versions in `Cargo.toml` (with shared version)
  b. updates README
  d. commit the changes
  e. publish crates in order
2. `git tag && git push && git push --tags` after release succeeds
3. On tag push, GitHub Release is created by GitHub Action with generated changelog based on config
4. Prepend the release body and any notes to CHANGELOG? This might be weird because it comes after the tag.

#### Full Automation

I think it's best if we could automate all the steps:

1. Whenever a PR is merged, a draft release is created/updated based on the changes since the last release. The next version (the tag to use) is derived from the labels of merged PRs.
    - `release-drafter` can do this, but not sure if `action-gh-release` can be used.
    - I think it's possible to write a job that simply derives the next version based on the merged PRs since the last release, and let GitHub generator do the generation.
2. Whenever a draft release is created/updated, a special PR to trigger the next release is created/updated. This should be possible with GitHub Action triggered on `release.created` and `release.edited`.
    - The body of the PR is derived from the draft release's body, listing the changes.
    - The PR contains the changes from `cargo release $version` where `$version` is the derived tag from the draft release. The PR also contains the updated CHANGELOG (prepending the release body after some transformations to make links work) and the updated README.
    - The PR itself will have a label to exclude itself from the changelog generation to avoid updating the release draft when it's merged.
    - The PR will be kept up to date by a job by resetting, rebasing and reapplying the changes each time triggered.
3. When we're ready to release the next version, we review the PR and merge it. If we want to add any special notes to the CHANGELOG, we can push to this PR just before merging.
4. When this special PR to trigger the release is merged, the draft release is finalized at the latest `master`. This can be done by an action triggered by push to `master` that checks if the commit is associated with a PR, and checking the PR.
5. The tag created from finalizing the release triggers the action to publish crates with the version.

**Comment by clux** [comment]
I think in theory the full-automation could work, but I am perfectly happy with the your middle one there as a stop-gap.

There are a few concerns I have with the full automation, it sounds like it would require a bit more work than the native solutions to do full automation; AFAIKT, we will not get the same standard contributor recognition that the automatic github changelog gives us out of the box. It also is probably a bit noisier than just doing one wrap-up from a generator at the end.

That said, I think we could work towards this with some experimentation though.

Initially, let us at least decide on categories and add some standard labels for our categories first so that we can try to categorise our next release. I propose the following labels:

- `change-fix` - for a `Fixed` category
- `change-new` or `change-add` for an `Added` category
- `change-modified` for a `Modified` category

**Comment by kazk** [comment]
As far as I can tell, the native generator is [controlled by a boolean parameter in GitHub API](https://github.com/softprops/action-gh-release/blob/b260a9f8a62be503314217fd25e904e2ac7cda72/src/github.ts#L94-L96), so the full automation can use the same native generator by creating a release with the flag on. The generated changelog seems to get appended.

Anyway, we can focus on the changelogs first.

---

I think [Keep a Changelog](https://keepachangelog.com/en/1.0.0/) format is a good convention to follow that's familiar to many. They have the following types:

- `Added` for new features.
- `Changed` for changes in existing functionality.
- `Deprecated` for soon-to-be removed features.
- `Removed` for now removed features.
- `Fixed` for any bug fixes.
- `Security` in case of vulnerabilities.

I propose labels based on these. So, basically, your proposal with more consistency, and a different common prefix (`ct = change type`) to avoid `change-change`.

- `ct-add`
- `ct-change`
- `ct-deprecate`
- `ct-remove`
- `ct-fix`
- `ct-ignore` (exclude from changelog)

I think imperative, present tense, is better for labels on PRs and these words are clear and consistent. The common prefix can be something else, even emoji like :package: (`:package:`).

**Comment by kazk** [comment]
I fixed the links in https://github.com/kube-rs/kube-rs/releases/tag/0.65.0 and mentioned contributors. The avatars are now shown.

**Comment by kazk** [comment]
> - [generated links are now wrong](https://github.com/kube-rs/kube-rs/releases) (`/issues` vs `/pull`) used to work on `/issues` always, but have stopped working

Looks like GitHub fixed this bug (we shouldn't be the only one relying on this). It now redirects like before. Try links on https://github.com/kube-rs/kube-rs/releases/tag/0.64.0 .

**Comment by clux** [comment]
> The list of avatars is a [separate feature](https://github.blog/changelog/2021-09-14-releases-now-have-an-avatar-list/). Avatars of users mentioned in the release are shown.

Ah, that is great. Then there's probably nothing major holding us back from going down a tracking PR route.

Sidenote: if want to follow the keep-a-changelog site verbatim, then we need a reasonable link to the unreleased changes under the UNRELEASED section. A github compare link to the `unreleased-changes` branch would probably work.

> I think imperative, present tense, is better for labels on PRs and these words are clear and consistent. The common prefix can be something else, even emoji like package (`:package:`).

Agreed. I think those are better than my ones. For the prefix, maybe `rlog-` or `clog-`? I think that is less likely to require a lookup, while still short. Or if it's ok with longer, maybe just `changelog-`.

Categorisation note on multiple labels: Big PRs are likely to land in **multiple** changelog categories. This probably isn't a problem; it implicitly encourages smaller PRs, and I guess for those exceptional cases we can revise the final changelog branch with notes on the big PRs for each category.

**Comment by clux** [comment]
Added them for now under `clog-`, but happy to change the prefix. https://github.com/kube-rs/kube-rs/labels?q=clog


Maybe the ignore category should be named `clog-exclude` to be more explicit though.

**Comment by kazk** [comment]
`changelog-` might be better. `clog` sounds like it won't be released :laughing:

**Comment by clux** [comment]
Ah. True.. [Changed to `changelog-*`](https://github.com/kube-rs/kube-rs/labels?q=changelog+). I'll write a small note in the PULL_REQUEST_TEMPLATE about adding a changelog* label for prs.

**Comment by kazk** [comment]
I think it's fine for us to label them before merging.
If necessary, we can add a check to require every PR to have a `changelog-` label before merging.

**Comment by clux** [comment]
Carrying on gently with some initial automation for this in #784 for `0.66.0`.

**Comment by clux** [comment]
Release done with this system in [0.66.0 release](https://github.com/kube-rs/kube-rs/releases/tag/0.66.0), and [here's the changelog](https://github.com/kube-rs/kube-rs/blob/master/CHANGELOG.md) after back-ports from generated.

Probably could have formatted the inital news a bit better (linking from headline to PRs directly e.g.), but feels like a good initial release. At least it gets to take advantage of your initial configuration!

**Comment by clux** [comment]
I do quite like the current setup now: writing 0-3 paragraphs of importance above the autogenerated stuff while the release is in a draft.

Some effects of this approach that I did not consider initially:

- we can hold off on making the release public until the docs.rs build is done (and link to changes in interfaces)
- it's typically at the end where it makes sense to decide what we should inject as the header (which prs were the most impactful / has important breaking changes) 
- we can keep the release in a draft stage post cargo release, but discuss how the gh release looks outside a PR (arguably not a PRO, but it elides wasting compute in CI, and elides notifying everyone who is watching the repo)

For the last point, if needed, we could have a little group chat, make a discussion for it, or possibly even use the [discussion_category_name](https://github.com/softprops/action-gh-release#-customizing) for the release.

We can also elide this step altogether by stating what we think should be highlighted in each PR as we go along, then the releaser extracts that blurb into the release before publishing it.
