### ISSUE TITLE
[kube-core] Validation error should show detail error message

### ISSUE THREAD

**Issue by XUJiahua** [kube-rs/kube-rs#777]
Maybe it would be better if Validation error show detail error message, so that user can easily find his issue.
![image](https://user-images.githubusercontent.com/1501598/148365352-34971297-267b-47cb-bba8-e4b805260383.png)

https://github.com/kube-rs/kube-rs/blob/4d991fe40d0ebbf3a20210308284bf196aa6f8a5/kube-core/src/request.rs?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L18

**Comment by clux** [comment]
Yeah, this should match what we do elsewhere. Other string errors are also generally included in the display on the error. Thank you.
