### ISSUE TITLE
runtime: Don't require `dashmap` to use `watcher`

### ISSUE THREAD

**Issue by olix0r** [kube-rs/kube-rs#781]
### Would you like to work on this feature?

We'd be happy to help implement this when we understand what solution would be acceptable.

### What problem are you trying to solve?

We use only `kube::runtime::watcher` from `kube_runtime` and incur unnecessary dependencies like `dashmap` which are only used by `kube::runtime::reflector`. I'd love to be able to avoid unnecessary dependencies. This helps reduce security alerts, compile times, and potential duplicate dependencies.

### Describe the solution you'd like

The easiest solution is probably to add a `kube_runtime/reflector` feature that optionally enables the reflector (and dash map). This would have to be wired through the higher level `Kube` crate so we could opt-in to `runtime` without `runtime-reflector`.

### Describe alternatives you've considered

Alternatively, we could split out a `kube_watcher` crate that is used by `kube_runtime` so we could opt into `watcher` without incurring the rest of the runtime dependencies. This might make things simpler than having to wrestle feature flags through `kube`; but I'm not sure of the appetite for changing the crate layout.

Specifically, I think the feature-flag approach would require disabling the reflector feature by default. The crate approach would allow the runtime crate to always enable the reflector.

### Target crate for feature

kube-runtime

**Comment by teozkr** [comment]
I think it'd make sense to move `watcher` into `kube_client`. The question (and I think we discussed this before) would be how we want to integrate it into `Api`. Then again, maybe it'd make sense to just move the module wholesale as a first step, and wait with deeper integration for later?

**Comment by olix0r** [comment]
`watcher` currently depends on `runtime::utils::ResetTimerBackoff`. should the utils (at least `ResetTimerBackoff` and `try_flatten_*`) also be moved into client?

**Comment by teozkr** [comment]
`ResetTimerBackoff` and `try_flatten_*` would probably make sense to migrate, yes, though we have been talking about moving the API surface of those into some `StreamExt` trait. Maybe it would make sense to make use of the natural API break here to make that move as well?

Then again, the compatibility wrappers for that would be trivial anyway, so it would probably be fine to punt on it for now.

**Comment by clux** [comment]
hm, i'm not entirely sure about this. `kube-client` is intended to mimic api features only, and the watch mechanisms is a little more runtime choice imo (especially if we have to port streambackoffs, our own events wrappers and flatten utils).

it might make more sense to put a default-enabled "cache" feature on `kube` to propagate into `kube-runtime` and have this cause a disabling of `reflector` and `controller` modules.

**Comment by olix0r** [comment]
@clux I think the problem here is the interaction of default features... If `kube` has a feature `cache` which enables `kube-runtime/controller`, it enables `kube-runtime` by default. If `kube-runtime` enables this feature by default, I think there's functionally no way disable the feature when using `kube`.

**Comment by clux** [comment]
Good point. I forgot that runtime was not a default feature. I guess the way to do it with features then would be as you have done.

It does mean that the main change here would be to default-disable controller and reflector modules. I am open to that, it's not always needed. WDYT @teozkr ?

**Comment by olix0r** [comment]
Alternatively: we could simply drop the `DashMap` dependency in favor of a `parking_lot::RwLock<HashMap<..>>`? I'm doubtful that any controller is going to actually need particularly high-throughput/low-latency access.  We already take a parking lot dependency via `tokio` (because, in Linkerd, we enable this feature in tokio). This would satisfy our goals without the need to introduce additional feature flags.

**Comment by clux** [comment]
I would also be open to experiments along that line. I have not been impressed with the speed of dashmap in even low frequency use environments.

Doing this might change the Store api though, and that might require since more diligent thinking (I have been wanting more methods available on that anyway).

**Comment by teozkr** [comment]
So.. this is basically the reason that we don't expose the `DashMap` itself (or any references to the objects) from the `Store`. It was always more of a stopgap solution than something that I was super in love with.

Ideally, I'd love to see the backing store traitified, which should also help out the use-case of wanting more exposed access methods. In that case I'd be fine with seeing `RwLock<HashMap>` be the default implementation.

Barring that, I'd be fine with just switching out the backend implementation as long as we can have some idea of what the perf impact is.

**Comment by olix0r** [comment]
> I'd be fine with just switching out the backend implementation as long as we can have some idea of what the perf impact is.

My basic assumptions are:

* there should only be noticeable perf hit when there is actual concurrent access (i.e., the lock is contended);
* there will never actually be concurrent writes, since all updates are driven from a single watch/task;
* concurrent reads should be pretty cheap, as long as they don't contend with a write;
  * because `Store` doesn't expose any guarded references, it's not possible for applications to cause a lock to be held indefinitely
  * the main concerns, then, are:
    * time spent hashing a key for lookups; and
    * time spent in allocation (e.g. cloning resources).
* so, the primary difference we'd expect to see is in workloads where there is both heavy read-load _and_ frequent writes.

we could mitigate some of the lock contention by:
* changing the cache to store `Arc<K>` values so cloning is cheaper, but this would change the public API for `reflector`;
* changing the map's hasher to [`FxHash`](https://docs.rs/fxhash/0.2.1/fxhash/) or, more likely, [`AHash`](https://crates.io/crates/ahash) (since I think we probably want DoS-resistance).
  * we could also look at `hashbrown::HashMap`, which uses `AHash` by default

The dashmap authors provide [benchmarking results](https://github.com/xacrimon/conc-map-bench), but I think we should be a little skeptical about these results in the context of a kubernetes controller where most operations are coupled with network operations where message deserialization is likely to outweigh any of the costs we encounter in map access.

This is all to say: if we want to go down the path of benchmarking this, we probably want to do so in the context of a full controller/application. My hunch is that microbenchmarks are not going to be very informative about actual performance characteristics.
