### ISSUE TITLE
CustomResource derive macro is rendering an unqualified Result

### ISSUE THREAD

**Issue by danrspencer** [kube-rs/kube-rs#794]
### Current and expected behavior

After upgrading to the latest version of kube-rs all of our custom resources started complaining about a `Result` being provided 2 generic arguments rather than 1. We use the pattern of creating an aliased version of `Result` tied to the crate's `Error`, so all of our instances of `Result` only expect a single generic.

```
pub type Result<T> = std::result::Result<T, crate::error::Error>;
```

After looking at the code for the `CustomResource` derive macro it appears to be being caused by the `serialize` function rendered by `#[derive(CustomResource)]`.

```
 fn serialize<S: #serde::Serializer>(&self, ser: S) -> Result<S::Ok, S::Error> {
 ```

From: [kube-derive/src/custom_resource.rs#L274](https://github.com/kube-rs/kube-rs/blob/3d5f90d44c21b3512ca0ecbb75a92998d5410f8e/kube-derive/src/custom_resource.rs#L274)

### Possible solution

The macro should render a fully qualified path to `Result` for all occurrences. 

For example:

```
 fn serialize<S: #serde::Serializer>(&self, ser: S) -> Result<S::Ok, S::Error> {
```

Becomes

```
 fn serialize<S: #serde::Serializer>(&self, ser: S) -> std::result::Result<S::Ok, S::Error> {
```

### Environment

N/A

### Affected crates

kube-derive

**Comment by teozkr** [comment]
We should probably fix this, yeah.

In the meantime, you can redefine your alias like this:

```rust
pub type Result<T, E = crate::error::Error> = std::result::Result<T, E>;
```

Which allows usage as both `Result<T>` and `Result<T, E>`.
