### ISSUE TITLE
Kube-rs config inference doesn't match kubectl

### ISSUE THREAD

**Issue by teozkr** [kube-rs/kube-rs#818]
### Current and expected behavior

`kubectl` and `kube::Config::infer()` should always connect to the same cluster.

Currently, `kube::Config::infer()` prefers in-cluster config if available, while `kubectl` prefers Kubeconfig files.

### Possible solution

`kube::Config` should prefer Kubeconfig as well.

### Environment

Not sure, this was on a coworker's screenshare.

### Affected crates

kube-client

### Would you like to work on fixing this bug?

yes

**Comment by clux** [comment]
Yeah, that's a fair thing to fix. I would not have thought this was something people could hit normally, because it requires both a kubeconfig and in-cluster evars/files, but consistency here makes sense. :+1:

**Comment by teozkr** [comment]
Yeah, this is definitely more in the "huh, I could imagine spending hours trying to figure out WTF is going wrong when hitting this" box than an urgent issue I've hit.
