### ISSUE TITLE
v0.70 Action::requeue_arget: None

### ISSUE THREAD

**Issue by webern** [kube-rs/kube-rs#860]
### Current and expected behavior

There is no way to construct an `Action` object with `requeue_after` value `None`

### Possible solution

Create a constructor for that case.

### Additional context

x

### Environment

v0.70

### Configuration and features

x

**Comment by webern** [comment]
Oops nevermind await_change is what I'm looking for

**Comment by webern** [comment]
btw I was using constants for these. These two constructors could be `pub const fn requeue` and `pub const fn await_change`

**Comment by clux** [comment]
That is true! Would that change anything meaningful if it's used within `reconcile`?

**Comment by webern** [comment]
> That is true! Would that change anything meaningful if it's used within `reconcile`?

No, it would only be meaningful for something like 

```rust
const REQUEUE: Action = Action::requeue(Duration::from_secs(3));
```

**Comment by clux** [comment]
If you think it's useful we could open an issue about going through and constify a couple of things in our interface. It's probably not the first thing I would prioritise though.
