### ISSUE TITLE
Publishing events for cluster scoped resources broken for Kube <1.23

### ISSUE THREAD

**Issue by louismrose** [kube-rs/kube-rs#870]
### Current and expected behavior

Publishing an event for a cluster scoped resource fails for the following Kubernetes versions:
* 1.22.2 and earlier
* 1.21.5 and earlier
* 1.20.11 and earlier

To reproduce:
1. Spin up a cluster with one of the affected versions
2. Run the test: `test::event_recorder_attaches_events_without_namespace` in `kube::runtime::events`

Expected behaviour:
This test should pass on all Kubernetes versions > 1.19.

### Possible solution

The problem is caused by `kube-rs` attempting to create events for cluster scoped resources in the `default` namespace. This is only supported since Kubernetes 1.23 (and was back ported to Kubernetes 1.22.3, 1.21.6 and 1.20.12). See: https://github.com/kubernetes/kubernetes/pull/100125

I think that `kube-rs` should provide the option to instead create events for cluster scoped resources in the `kube-system` namespace, which is supported since Kubernetes 1.19.

Perhaps `Recorder#new` could take an additional enum param, or perhaps a `Recorder#new...xxx` function could be added.

### Additional context

A workaround for now is to inline the `Recorder` struct and impl into client code, and to change the default namespace in `new` from `default` to `kube-system`.

### Environment

```
$ k version --short
Client Version: v1.22.1
Server Version: v1.21.1
```

Though please see earlier comments about Kubernetes versions.

### Configuration and features

```
$ cargo tree -i k8s-openapi
k8s-openapi v0.14.0
├── cohesity_view_custom_resources v0.1.0 (/Users/louisrose/Code/model-analysis-platform/operators/workspaces/lib/cohesity_view_custom_resources)
│   └── snapshot_controller v0.1.0 (/Users/louisrose/Code/model-analysis-platform/operators/workspaces/bin/snapshot_controller)
├── efs_folder_custom_resources v0.1.0 (/Users/louisrose/Code/model-analysis-platform/operators/workspaces/lib/efs_folder_custom_resources)
│   └── snapshot_controller v0.1.0 (/Users/louisrose/Code/model-analysis-platform/operators/workspaces/bin/snapshot_controller)
├── kube v0.70.0
│   ├── cohesity_view_custom_resources v0.1.0 (/Users/louisrose/Code/model-analysis-platform/operators/workspaces/lib/cohesity_view_custom_resources) (*)
│   ├── efs_folder_custom_resources v0.1.0 (/Users/louisrose/Code/model-analysis-platform/operators/workspaces/lib/efs_folder_custom_resources) (*)
│   ├── snapshot_controller v0.1.0 (/Users/louisrose/Code/model-analysis-platform/operators/workspaces/bin/snapshot_controller)
│   └── snapshot_custom_resources v0.1.0 (/Users/louisrose/Code/model-analysis-platform/operators/workspaces/lib/snapshot_custom_resources)
│       └── snapshot_controller v0.1.0 (/Users/louisrose/Code/model-analysis-platform/operators/workspaces/bin/snapshot_controller)
├── kube-client v0.70.0
│   ├── kube v0.70.0 (*)
│   └── kube-runtime v0.70.0
│       └── kube v0.70.0 (*)
├── kube-core v0.70.0
│   ├── kube v0.70.0 (*)
│   └── kube-client v0.70.0 (*)
├── kube-runtime v0.70.0 (*)
├── snapshot_controller v0.1.0 (/Users/louisrose/Code/model-analysis-platform/operators/workspaces/bin/snapshot_controller)
└── snapshot_custom_resources v0.1.0 (/Users/louisrose/Code/model-analysis-platform/operators/workspaces/lib/snapshot_custom_resources) (*)
```

```
$ cargo tree | grep kube
│   ├── kube v0.70.0
│   │   ├── kube-client v0.70.0
│   │   │   ├── kube-core v0.70.0
│   │   ├── kube-core v0.70.0 (*)
│   │   ├── kube-derive v0.70.0 (proc-macro)
│   │   └── kube-runtime v0.70.0
│   │       ├── kube-client v0.70.0 (*)
│   ├── kube v0.70.0 (*)
├── kube v0.70.0 (*)
│   ├── kube v0.70.0 (*)
```

### Affected crates

kube-runtime

### Would you like to work on fixing this bug?

maybe

**Comment by clux** [comment]
Great bug. Thank you. Reproduced locally vs k3d on 1.21.3 with:

```sh
cargo test -p kube-runtime test::event_recorder_attaches_events_without_namespace -- --ignored
```
```
Error: Api(ErrorResponse { status: "Failure", message: "Event \"kube-vpn4n\" is invalid: involvedObject.namespace: Invalid value: \"\": does not match event.namespace", reason: "Invalid", code: 422 })
thread 'events::test::event_recorder_attaches_events_without_namespace' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `0`: the test returned a termination value with a non-zero status code (1) which indicates a failure', /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/test/src/lib.rs:187:5
```

**Comment by teozkr** [comment]
Looks like the correct answer would be to just always write the events to `kube-system` then?

**Comment by clux** [comment]
I kind of feel like `default` should be our default, as it makes the most sense semantically (discussed in #847), and it soon enough will be prevalent: they backported it to 1.22, and this is a pretty new api anyway.

Maybe we can provide a temporary override to avoid spamming `kube-system`?

e.g.:

```rust
Recorder::new(client, reporter, objref).namespace("kube-system")
```

**Comment by teozkr** [comment]
The changelog line:

> kube-apiserver: events created via the `events.k8s.io` API group for cluster-scoped objects are now permitted in the default namespace as well for compatibility with events clients and the `v1` API

Implies that allowing `default` is just a compatibility thing, and that `kube-system` is still canonical.

**Comment by clux** [comment]
Ah ok. Let's just change it to `kube-system` for now then.
