### ISSUE TITLE
Access to the API Server version

### ISSUE THREAD

**Issue by olix0r** [kube-rs/kube-rs#940]
### Would you like to work on this feature?

maybe

### What problem are you trying to solve?

I'd like to be able to discover the Kubernetes API Server's version.  `client-go` exposes a [`ServerVersion()`](https://github.com/kubernetes/client-go/blob/acab036eff5706db06b4eb79253165cf4be0d9c5/discovery/discovery_client.go#L396-L407) helper.

### Describe the solution you'd like

This probably needs to be exposed off of `client`, since there's no specific API resource type for this.

### Describe alternatives you've considered

🤷 

### Target crate for feature

kube-client

**Comment by clux** [comment]
Heyhey. We do have [`Client::apiserver_version`](https://docs.rs/kube/latest/kube/struct.Client.html#method.apiserver_version), is that sufficient? It's possibly placed in a bit of an unintuitive place and should perhaps be referenced from `Discovery` instead :thinking:

**Comment by olix0r** [comment]
Excellent! Not sure how I missed that.
